// <auto-generated>
// This file was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#ifndef hammer_GEN_H
#define hammer_GEN_H
extern void *g_phammerLibrary;
extern bool g_bIshammerInitialized;

#include "windows.h" 
#include "engine/structs.h" 
#ifdef _WIN32
#define CC __stdcall
#else
#define CC
#endif

#define RW_VAR(type, name, parent, readop, writeop) RWVariable<type, parent> name{readop, writeop,this};
#define ConVar _ConVar
#define ConCommand _ConCommand
#define CUtlBuffer _CUtlBuffer
#define CUtlString _CUtlString
#define CUtlVector _CUtlVector


extern void *g_hammer_nativeFunctions[616];
extern void *g_hammer_callbackFunctions[61];
extern int g_hammer_iStructSizes[143];
typedef int(*FnBindingsImportDelegate)( int hash, void* imports, void* exports, int* structSizes );

inline void hammerBindingsInitialize()
{
	if ( g_bIshammerInitialized ) return;
	
	g_phammerLibrary = LoadLibraryA("tools/hammer.dll");
	if(!g_phammerLibrary)
		_exit(1);
	
	FnBindingsImportDelegate igen_hammer = (FnBindingsImportDelegate)GetProcAddress( (HMODULE)g_phammerLibrary, "igen_hammer" );
	if(!igen_hammer)
		_exit(1);
	
	void *managedFunctions[61] = 
	
	{
		(void*) (g_hammer_callbackFunctions[0]),
		(void*) (g_hammer_callbackFunctions[1]),
		(void*) (g_hammer_callbackFunctions[2]),
		(void*) (g_hammer_callbackFunctions[3]),
		(void*) (g_hammer_callbackFunctions[4]),
		(void*) (g_hammer_callbackFunctions[5]),
		(void*) (g_hammer_callbackFunctions[6]),
		(void*) (g_hammer_callbackFunctions[7]),
		(void*) (g_hammer_callbackFunctions[8]),
		(void*) (g_hammer_callbackFunctions[9]),
		(void*) (g_hammer_callbackFunctions[10]),
		(void*) (g_hammer_callbackFunctions[11]),
		(void*) (g_hammer_callbackFunctions[12]),
		(void*) (g_hammer_callbackFunctions[13]),
		(void*) (g_hammer_callbackFunctions[14]),
		(void*) (g_hammer_callbackFunctions[15]),
		(void*) (g_hammer_callbackFunctions[16]),
		(void*) (g_hammer_callbackFunctions[17]),
		(void*) (g_hammer_callbackFunctions[18]),
		(void*) (g_hammer_callbackFunctions[19]),
		(void*) (g_hammer_callbackFunctions[20]),
		(void*) (g_hammer_callbackFunctions[21]),
		(void*) (g_hammer_callbackFunctions[22]),
		(void*) (g_hammer_callbackFunctions[23]),
		(void*) (g_hammer_callbackFunctions[24]),
		(void*) (g_hammer_callbackFunctions[25]),
		(void*) (g_hammer_callbackFunctions[26]),
		(void*) (g_hammer_callbackFunctions[27]),
		(void*) (g_hammer_callbackFunctions[28]),
		(void*) (g_hammer_callbackFunctions[29]),
		(void*) (g_hammer_callbackFunctions[30]),
		(void*) (g_hammer_callbackFunctions[31]),
		(void*) (g_hammer_callbackFunctions[32]),
		(void*) (g_hammer_callbackFunctions[33]),
		(void*) (g_hammer_callbackFunctions[34]),
		(void*) (g_hammer_callbackFunctions[35]),
		(void*) (g_hammer_callbackFunctions[36]),
		(void*) (g_hammer_callbackFunctions[37]),
		(void*) (g_hammer_callbackFunctions[38]),
		(void*) (g_hammer_callbackFunctions[39]),
		(void*) (g_hammer_callbackFunctions[40]),
		(void*) (g_hammer_callbackFunctions[41]),
		(void*) (g_hammer_callbackFunctions[42]),
		(void*) (g_hammer_callbackFunctions[43]),
		(void*) (g_hammer_callbackFunctions[44]),
		(void*) (g_hammer_callbackFunctions[45]),
		(void*) (g_hammer_callbackFunctions[46]),
		(void*) (g_hammer_callbackFunctions[47]),
		(void*) (g_hammer_callbackFunctions[48]),
		(void*) (g_hammer_callbackFunctions[49]),
		(void*) (g_hammer_callbackFunctions[50]),
		(void*) (g_hammer_callbackFunctions[51]),
		(void*) (g_hammer_callbackFunctions[52]),
		(void*) (g_hammer_callbackFunctions[53]),
		(void*) (g_hammer_callbackFunctions[54]),
		(void*) (g_hammer_callbackFunctions[55]),
		(void*) (g_hammer_callbackFunctions[56]),
		(void*) (g_hammer_callbackFunctions[57]),
		(void*) (g_hammer_callbackFunctions[58]),
		(void*) (g_hammer_callbackFunctions[59]),
		(void*) (g_hammer_callbackFunctions[60]),
	};
	
	igen_hammer( *(unsigned short*)(((uint64_t)igen_hammer)+8), managedFunctions, g_hammer_nativeFunctions, g_hammer_iStructSizes );
	g_bIshammerInitialized = true;
}
class CHammerApp
{
	public:
	void *m_pSelf;
	inline operator CHammerApp*()
	{
		return (CHammerApp*)m_pSelf;
	}
	inline void RefreshEntitiesGameData() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[1])(m_pSelf);
	}
	inline HMaterialStrong* GetCurrentMaterial() 
	{
		return
		((HMaterialStrong*(*)(void* __self))g_hammer_nativeFunctions[2])(m_pSelf);
	}
	inline void SetCurrentTexture(const char* assetFilename) 
	{
		((void(*)(void* __self, const char* __assetFilename))g_hammer_nativeFunctions[3])(m_pSelf, assetFilename);
	}
	inline int GetActiveMapAsset() 
	{
		return
		((int(*)(void* __self))g_hammer_nativeFunctions[4])(m_pSelf);
	}
	inline int GetActiveMapDoc() 
	{
		return
		((int(*)(void* __self))g_hammer_nativeFunctions[5])(m_pSelf);
	}
	inline void MarkAllViewHudsDirty() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[6])(m_pSelf);
	}
	inline void SelectObjectsUsingAsset(const char* assetFilename) 
	{
		((void(*)(void* __self, const char* __assetFilename))g_hammer_nativeFunctions[7])(m_pSelf, assetFilename);
	}
	inline void SelectFacesUsingMaterial(const char* assetFilename) 
	{
		((void(*)(void* __self, const char* __assetFilename))g_hammer_nativeFunctions[8])(m_pSelf, assetFilename);
	}
	inline void AssignAssetToSelection(const char* assetFilename) 
	{
		((void(*)(void* __self, const char* __assetFilename))g_hammer_nativeFunctions[9])(m_pSelf, assetFilename);
	}
	inline void ShowEntityReportForAsset(const char* assetFilename) 
	{
		((void(*)(void* __self, const char* __assetFilename))g_hammer_nativeFunctions[10])(m_pSelf, assetFilename);
	}
	inline void OnFileReload() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[11])(m_pSelf);
	}
};
class CHammerEditorSession
{
	public:
	void *m_pSelf;
	inline operator CHammerEditorSession*()
	{
		return (CHammerEditorSession*)m_pSelf;
	}
	inline void ShowLoadingProgressBar() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[12])(m_pSelf);
	}
	inline void HideLoadingProgressBar() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[13])(m_pSelf);
	}
	inline const IAsset* GetMapAsset() 
	{
		return
		((const IAsset*(*)(void* self))g_hammer_nativeFunctions[14])(m_pSelf);
	}
	inline int GetMapDoc() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[15])(m_pSelf);
	}
};
class CHistory
{
	public:
	void *m_pSelf;
	inline operator CHistory*()
	{
		return (CHistory*)m_pSelf;
	}
	inline void MarkUndoPosition(CSelection* pSelection, const char* pszName) 
	{
		((void(*)(void* self, CSelection* pSelection, const char* pszName))g_hammer_nativeFunctions[16])(m_pSelf, pSelection, pszName);
	}
	inline void Keep(CMapNode* pUndoable) 
	{
		((void(*)(void* self, CMapNode* pUndoable))g_hammer_nativeFunctions[17])(m_pSelf, pUndoable);
	}
	inline void KeepNew(CMapNode* pUndoable) 
	{
		((void(*)(void* self, CMapNode* pUndoable))g_hammer_nativeFunctions[18])(m_pSelf, pUndoable);
	}
	static
	inline const CHistory* GetHistory() 
	{
		return
		((const CHistory*(*)())g_hammer_nativeFunctions[19])();
	}
};
class CMapDoc
{
	public:
	void *m_pSelf;
	inline operator CMapDoc*()
	{
		return (CMapDoc*)m_pSelf;
	}
	inline int GetMapWorld() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[20])(m_pSelf);
	}
	inline const char* GetPathName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[21])(m_pSelf);
	}
	inline const CSelection* GetSelection() 
	{
		return
		((const CSelection*(*)(void* self))g_hammer_nativeFunctions[22])(m_pSelf);
	}
	inline void AddObjectToDocument(CMapNode* pObject, CMapNode* pParent) 
	{
		((void(*)(void* self, CMapNode* pObject, CMapNode* pParent))g_hammer_nativeFunctions[23])(m_pSelf, pObject, pParent);
	}
	inline void DeleteObject(CMapNode* node) 
	{
		((void(*)(void* self, CMapNode* node))g_hammer_nativeFunctions[24])(m_pSelf, node);
	}
	inline int CreateEmptyMesh(int addToDocument) 
	{
		return
		((int(*)(void* self, int addToDocument))g_hammer_nativeFunctions[25])(m_pSelf, addToDocument);
	}
	inline int CreateEntity(int addToDocument) 
	{
		return
		((int(*)(void* self, int addToDocument))g_hammer_nativeFunctions[26])(m_pSelf, addToDocument);
	}
	inline int CreateGameObject(int addToDocument) 
	{
		return
		((int(*)(void* self, int addToDocument))g_hammer_nativeFunctions[27])(m_pSelf, addToDocument);
	}
	inline void CreateMapGroup() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[28])(m_pSelf);
	}
	inline void CreateMapInstance() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[29])(m_pSelf);
	}
	inline void CreateMapPath() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[30])(m_pSelf);
	}
	inline void CreateStaticOverlay() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[31])(m_pSelf);
	}
};
class CMapEntity
{
	public:
	void *m_pSelf;
	inline operator CMapEntity*()
	{
		return (CMapEntity*)m_pSelf;
	}
	//NativeMapDoc.CMapEntity.__N.From_CMapNode_To_CMapEntity = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[32];
	//NativeMapDoc.CMapEntity.__N.To_CMapNode_From_CMapEntity = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[33];
	inline const char* GetClassName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[34])(m_pSelf);
	}
	inline void SetClass(const char* classname) 
	{
		((void(*)(void* self, const char* classname))g_hammer_nativeFunctions[35])(m_pSelf, classname);
	}
	inline void SetKeyValue(const char* key, const char* value) 
	{
		((void(*)(void* self, const char* key, const char* value))g_hammer_nativeFunctions[36])(m_pSelf, key, value);
	}
	inline const char* GetKeyValue(const char* key) 
	{
		return
		((const char*(*)(void* self, const char* key))g_hammer_nativeFunctions[37])(m_pSelf, key);
	}
	inline int TargetNameMatches(const char* name) 
	{
		return
		((int(*)(void* self, const char* name))g_hammer_nativeFunctions[38])(m_pSelf, name);
	}
	inline void SetDefaultBounds(Vector minBounds, Vector maxBounds) 
	{
		((void(*)(void* __self, Vector __minBounds, Vector __maxBounds))g_hammer_nativeFunctions[39])(m_pSelf, minBounds, maxBounds);
	}
	inline int GetNodeID() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[40])(m_pSelf);
	}
	inline const char* GetName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[41])(m_pSelf);
	}
	inline void SetName(const char* name) 
	{
		((void(*)(void* self, const char* name))g_hammer_nativeFunctions[42])(m_pSelf, name);
	}
	inline int GetParent() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[43])(m_pSelf);
	}
	inline void SetParent(CMapNode* parent) 
	{
		((void(*)(void* self, CMapNode* parent))g_hammer_nativeFunctions[44])(m_pSelf, parent);
	}
	inline int GetParentWorld() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[45])(m_pSelf);
	}
	inline int GetRootDocument(int64 nDocumentLoaded) 
	{
		return
		((int(*)(void* self, int64 nDocumentLoaded))g_hammer_nativeFunctions[46])(m_pSelf, nDocumentLoaded);
	}
	inline const char* GetDescription() 
	{
		return
		((const char*(*)(void* __self))g_hammer_nativeFunctions[47])(m_pSelf);
	}
	inline const char* GetTypeString() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[48])(m_pSelf);
	}
	inline int Copy() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[49])(m_pSelf);
	}
	inline int IsVisible() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[50])(m_pSelf);
	}
	inline void SetVisible(int bVisible) 
	{
		((void(*)(void* self, int bVisible))g_hammer_nativeFunctions[51])(m_pSelf, bVisible);
	}
	inline int IsSelected() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[52])(m_pSelf);
	}
	inline int GetChildCount() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[53])(m_pSelf);
	}
	inline int GetChild(int i) 
	{
		return
		((int(*)(void* self, int i))g_hammer_nativeFunctions[54])(m_pSelf, i);
	}
	inline int GetFirstDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[55])(m_pSelf, pos);
	}
	inline int GetNextDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[56])(m_pSelf, pos);
	}
	inline int AsMapEntity() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[57])(m_pSelf);
	}
	inline Vector GetOrigin() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[58])(m_pSelf);
	}
	inline QAngle GetAngles() 
	{
		return
		((QAngle(*)(void* self))g_hammer_nativeFunctions[59])(m_pSelf);
	}
	inline Vector GetScales() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[60])(m_pSelf);
	}
	inline void SetOrigin(Vector origin) 
	{
		((void(*)(void* self, Vector origin))g_hammer_nativeFunctions[61])(m_pSelf, origin);
	}
	inline void SetAngles(QAngle angles) 
	{
		((void(*)(void* self, QAngle angles))g_hammer_nativeFunctions[62])(m_pSelf, angles);
	}
	inline void SetScales(Vector scales) 
	{
		((void(*)(void* self, Vector scales))g_hammer_nativeFunctions[63])(m_pSelf, scales);
	}
	inline void BeginTransformOperation(int64 nTransformType, int64 nFlags) 
	{
		((void(*)(void* self, int64 nTransformType, int64 nFlags))g_hammer_nativeFunctions[64])(m_pSelf, nTransformType, nFlags);
	}
	inline void Transform(VMatrix matrix, int64 nFlags) 
	{
		((void(*)(void* self, VMatrix matrix, int64 nFlags))g_hammer_nativeFunctions[65])(m_pSelf, matrix, nFlags);
	}
	inline void EndTransformOperation() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[66])(m_pSelf);
	}
	inline void MarkBoundsDirty() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[67])(m_pSelf);
	}
	inline void FullBoundsUpdate() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[68])(m_pSelf);
	}
	inline void SetModifiedFlag() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[69])(m_pSelf);
	}
	inline int GeneratesEntityModelGeometry() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[70])(m_pSelf);
	}
	inline void DescriptionChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[71])(m_pSelf);
	}
	inline void CoreAttributeChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[72])(m_pSelf);
	}
};
class CMapGameObject
{
	public:
	void *m_pSelf;
	inline operator CMapGameObject*()
	{
		return (CMapGameObject*)m_pSelf;
	}
	//NativeMapDoc.CMapGameObject.__N.From_CMapNode_To_CMapGameObject = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[73];
	//NativeMapDoc.CMapGameObject.__N.To_CMapNode_From_CMapGameObject = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[74];
	inline void SetGUID(const char* json) 
	{
		((void(*)(void* self, const char* json))g_hammer_nativeFunctions[75])(m_pSelf, json);
	}
	inline const char* GetGUID() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[76])(m_pSelf);
	}
	inline int GetNodeID() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[77])(m_pSelf);
	}
	inline const char* GetName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[78])(m_pSelf);
	}
	inline void SetName(const char* name) 
	{
		((void(*)(void* self, const char* name))g_hammer_nativeFunctions[79])(m_pSelf, name);
	}
	inline int GetParent() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[80])(m_pSelf);
	}
	inline void SetParent(CMapNode* parent) 
	{
		((void(*)(void* self, CMapNode* parent))g_hammer_nativeFunctions[81])(m_pSelf, parent);
	}
	inline int GetParentWorld() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[82])(m_pSelf);
	}
	inline int GetRootDocument(int64 nDocumentLoaded) 
	{
		return
		((int(*)(void* self, int64 nDocumentLoaded))g_hammer_nativeFunctions[83])(m_pSelf, nDocumentLoaded);
	}
	inline const char* GetDescription() 
	{
		return
		((const char*(*)(void* __self))g_hammer_nativeFunctions[84])(m_pSelf);
	}
	inline const char* GetTypeString() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[85])(m_pSelf);
	}
	inline int Copy() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[86])(m_pSelf);
	}
	inline int IsVisible() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[87])(m_pSelf);
	}
	inline void SetVisible(int bVisible) 
	{
		((void(*)(void* self, int bVisible))g_hammer_nativeFunctions[88])(m_pSelf, bVisible);
	}
	inline int IsSelected() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[89])(m_pSelf);
	}
	inline int GetChildCount() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[90])(m_pSelf);
	}
	inline int GetChild(int i) 
	{
		return
		((int(*)(void* self, int i))g_hammer_nativeFunctions[91])(m_pSelf, i);
	}
	inline int GetFirstDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[92])(m_pSelf, pos);
	}
	inline int GetNextDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[93])(m_pSelf, pos);
	}
	inline int AsMapEntity() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[94])(m_pSelf);
	}
	inline Vector GetOrigin() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[95])(m_pSelf);
	}
	inline QAngle GetAngles() 
	{
		return
		((QAngle(*)(void* self))g_hammer_nativeFunctions[96])(m_pSelf);
	}
	inline Vector GetScales() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[97])(m_pSelf);
	}
	inline void SetOrigin(Vector origin) 
	{
		((void(*)(void* self, Vector origin))g_hammer_nativeFunctions[98])(m_pSelf, origin);
	}
	inline void SetAngles(QAngle angles) 
	{
		((void(*)(void* self, QAngle angles))g_hammer_nativeFunctions[99])(m_pSelf, angles);
	}
	inline void SetScales(Vector scales) 
	{
		((void(*)(void* self, Vector scales))g_hammer_nativeFunctions[100])(m_pSelf, scales);
	}
	inline void BeginTransformOperation(int64 nTransformType, int64 nFlags) 
	{
		((void(*)(void* self, int64 nTransformType, int64 nFlags))g_hammer_nativeFunctions[101])(m_pSelf, nTransformType, nFlags);
	}
	inline void Transform(VMatrix matrix, int64 nFlags) 
	{
		((void(*)(void* self, VMatrix matrix, int64 nFlags))g_hammer_nativeFunctions[102])(m_pSelf, matrix, nFlags);
	}
	inline void EndTransformOperation() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[103])(m_pSelf);
	}
	inline void MarkBoundsDirty() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[104])(m_pSelf);
	}
	inline void FullBoundsUpdate() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[105])(m_pSelf);
	}
	inline void SetModifiedFlag() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[106])(m_pSelf);
	}
	inline int GeneratesEntityModelGeometry() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[107])(m_pSelf);
	}
	inline void DescriptionChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[108])(m_pSelf);
	}
	inline void CoreAttributeChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[109])(m_pSelf);
	}
};
class CMapGroup
{
	public:
	void *m_pSelf;
	inline operator CMapGroup*()
	{
		return (CMapGroup*)m_pSelf;
	}
	//NativeMapDoc.CMapGroup.__N.From_CMapNode_To_CMapGroup = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[110];
	//NativeMapDoc.CMapGroup.__N.To_CMapNode_From_CMapGroup = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[111];
	inline int GetNodeID() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[112])(m_pSelf);
	}
	inline const char* GetName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[113])(m_pSelf);
	}
	inline void SetName(const char* name) 
	{
		((void(*)(void* self, const char* name))g_hammer_nativeFunctions[114])(m_pSelf, name);
	}
	inline int GetParent() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[115])(m_pSelf);
	}
	inline void SetParent(CMapNode* parent) 
	{
		((void(*)(void* self, CMapNode* parent))g_hammer_nativeFunctions[116])(m_pSelf, parent);
	}
	inline int GetParentWorld() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[117])(m_pSelf);
	}
	inline int GetRootDocument(int64 nDocumentLoaded) 
	{
		return
		((int(*)(void* self, int64 nDocumentLoaded))g_hammer_nativeFunctions[118])(m_pSelf, nDocumentLoaded);
	}
	inline const char* GetDescription() 
	{
		return
		((const char*(*)(void* __self))g_hammer_nativeFunctions[119])(m_pSelf);
	}
	inline const char* GetTypeString() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[120])(m_pSelf);
	}
	inline int Copy() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[121])(m_pSelf);
	}
	inline int IsVisible() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[122])(m_pSelf);
	}
	inline void SetVisible(int bVisible) 
	{
		((void(*)(void* self, int bVisible))g_hammer_nativeFunctions[123])(m_pSelf, bVisible);
	}
	inline int IsSelected() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[124])(m_pSelf);
	}
	inline int GetChildCount() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[125])(m_pSelf);
	}
	inline int GetChild(int i) 
	{
		return
		((int(*)(void* self, int i))g_hammer_nativeFunctions[126])(m_pSelf, i);
	}
	inline int GetFirstDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[127])(m_pSelf, pos);
	}
	inline int GetNextDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[128])(m_pSelf, pos);
	}
	inline int AsMapEntity() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[129])(m_pSelf);
	}
	inline Vector GetOrigin() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[130])(m_pSelf);
	}
	inline QAngle GetAngles() 
	{
		return
		((QAngle(*)(void* self))g_hammer_nativeFunctions[131])(m_pSelf);
	}
	inline Vector GetScales() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[132])(m_pSelf);
	}
	inline void SetOrigin(Vector origin) 
	{
		((void(*)(void* self, Vector origin))g_hammer_nativeFunctions[133])(m_pSelf, origin);
	}
	inline void SetAngles(QAngle angles) 
	{
		((void(*)(void* self, QAngle angles))g_hammer_nativeFunctions[134])(m_pSelf, angles);
	}
	inline void SetScales(Vector scales) 
	{
		((void(*)(void* self, Vector scales))g_hammer_nativeFunctions[135])(m_pSelf, scales);
	}
	inline void BeginTransformOperation(int64 nTransformType, int64 nFlags) 
	{
		((void(*)(void* self, int64 nTransformType, int64 nFlags))g_hammer_nativeFunctions[136])(m_pSelf, nTransformType, nFlags);
	}
	inline void Transform(VMatrix matrix, int64 nFlags) 
	{
		((void(*)(void* self, VMatrix matrix, int64 nFlags))g_hammer_nativeFunctions[137])(m_pSelf, matrix, nFlags);
	}
	inline void EndTransformOperation() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[138])(m_pSelf);
	}
	inline void MarkBoundsDirty() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[139])(m_pSelf);
	}
	inline void FullBoundsUpdate() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[140])(m_pSelf);
	}
	inline void SetModifiedFlag() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[141])(m_pSelf);
	}
	inline int GeneratesEntityModelGeometry() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[142])(m_pSelf);
	}
	inline void DescriptionChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[143])(m_pSelf);
	}
	inline void CoreAttributeChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[144])(m_pSelf);
	}
};
class CMapInstance
{
	public:
	void *m_pSelf;
	inline operator CMapInstance*()
	{
		return (CMapInstance*)m_pSelf;
	}
	//NativeMapDoc.CMapInstance.__N.From_CMapNode_To_CMapInstance = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[145];
	//NativeMapDoc.CMapInstance.__N.To_CMapNode_From_CMapInstance = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[146];
	inline void SetTarget(CMapNode* node) 
	{
		((void(*)(void* self, CMapNode* node))g_hammer_nativeFunctions[147])(m_pSelf, node);
	}
	inline int GetTarget() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[148])(m_pSelf);
	}
	inline int GetNodeID() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[149])(m_pSelf);
	}
	inline const char* GetName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[150])(m_pSelf);
	}
	inline void SetName(const char* name) 
	{
		((void(*)(void* self, const char* name))g_hammer_nativeFunctions[151])(m_pSelf, name);
	}
	inline int GetParent() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[152])(m_pSelf);
	}
	inline void SetParent(CMapNode* parent) 
	{
		((void(*)(void* self, CMapNode* parent))g_hammer_nativeFunctions[153])(m_pSelf, parent);
	}
	inline int GetParentWorld() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[154])(m_pSelf);
	}
	inline int GetRootDocument(int64 nDocumentLoaded) 
	{
		return
		((int(*)(void* self, int64 nDocumentLoaded))g_hammer_nativeFunctions[155])(m_pSelf, nDocumentLoaded);
	}
	inline const char* GetDescription() 
	{
		return
		((const char*(*)(void* __self))g_hammer_nativeFunctions[156])(m_pSelf);
	}
	inline const char* GetTypeString() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[157])(m_pSelf);
	}
	inline int Copy() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[158])(m_pSelf);
	}
	inline int IsVisible() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[159])(m_pSelf);
	}
	inline void SetVisible(int bVisible) 
	{
		((void(*)(void* self, int bVisible))g_hammer_nativeFunctions[160])(m_pSelf, bVisible);
	}
	inline int IsSelected() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[161])(m_pSelf);
	}
	inline int GetChildCount() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[162])(m_pSelf);
	}
	inline int GetChild(int i) 
	{
		return
		((int(*)(void* self, int i))g_hammer_nativeFunctions[163])(m_pSelf, i);
	}
	inline int GetFirstDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[164])(m_pSelf, pos);
	}
	inline int GetNextDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[165])(m_pSelf, pos);
	}
	inline int AsMapEntity() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[166])(m_pSelf);
	}
	inline Vector GetOrigin() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[167])(m_pSelf);
	}
	inline QAngle GetAngles() 
	{
		return
		((QAngle(*)(void* self))g_hammer_nativeFunctions[168])(m_pSelf);
	}
	inline Vector GetScales() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[169])(m_pSelf);
	}
	inline void SetOrigin(Vector origin) 
	{
		((void(*)(void* self, Vector origin))g_hammer_nativeFunctions[170])(m_pSelf, origin);
	}
	inline void SetAngles(QAngle angles) 
	{
		((void(*)(void* self, QAngle angles))g_hammer_nativeFunctions[171])(m_pSelf, angles);
	}
	inline void SetScales(Vector scales) 
	{
		((void(*)(void* self, Vector scales))g_hammer_nativeFunctions[172])(m_pSelf, scales);
	}
	inline void BeginTransformOperation(int64 nTransformType, int64 nFlags) 
	{
		((void(*)(void* self, int64 nTransformType, int64 nFlags))g_hammer_nativeFunctions[173])(m_pSelf, nTransformType, nFlags);
	}
	inline void Transform(VMatrix matrix, int64 nFlags) 
	{
		((void(*)(void* self, VMatrix matrix, int64 nFlags))g_hammer_nativeFunctions[174])(m_pSelf, matrix, nFlags);
	}
	inline void EndTransformOperation() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[175])(m_pSelf);
	}
	inline void MarkBoundsDirty() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[176])(m_pSelf);
	}
	inline void FullBoundsUpdate() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[177])(m_pSelf);
	}
	inline void SetModifiedFlag() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[178])(m_pSelf);
	}
	inline int GeneratesEntityModelGeometry() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[179])(m_pSelf);
	}
	inline void DescriptionChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[180])(m_pSelf);
	}
	inline void CoreAttributeChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[181])(m_pSelf);
	}
};
class CMapMesh
{
	public:
	void *m_pSelf;
	inline operator CMapMesh*()
	{
		return (CMapMesh*)m_pSelf;
	}
	//NativeMapDoc.CMapMesh.__N.From_CMapNode_To_CMapMesh = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[182];
	//NativeMapDoc.CMapMesh.__N.To_CMapNode_From_CMapMesh = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[183];
	inline void AssignMaterialToMesh(const char* materialName) 
	{
		((void(*)(void* self, const char* materialName))g_hammer_nativeFunctions[184])(m_pSelf, materialName);
	}
	inline void ConstructFromData(int numVerticies, void* vertexPositions, void* vertexTexCoords, int numIndices, void* vertexIndices, int numFaces, void* faceVertexCounts, void* faceMaterialsPtr, int mergeVertices, float vertexMergeTolerance) 
	{
		((void(*)(void* self, int numVerticies, void* vertexPositions, void* vertexTexCoords, int numIndices, void* vertexIndices, int numFaces, void* faceVertexCounts, void* faceMaterialsPtr, int mergeVertices, float vertexMergeTolerance))g_hammer_nativeFunctions[185])(m_pSelf, numVerticies, vertexPositions, vertexTexCoords, numIndices, vertexIndices, numFaces, faceVertexCounts, faceMaterialsPtr, mergeVertices, vertexMergeTolerance);
	}
	inline void GetFaceMaterials(CUtlVector<CUtlString>* materials) 
	{
		((void(*)(void* __self, CUtlVector<CUtlString>* __materials))g_hammer_nativeFunctions[186])(m_pSelf, materials);
	}
	inline int GetNodeID() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[187])(m_pSelf);
	}
	inline const char* GetName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[188])(m_pSelf);
	}
	inline void SetName(const char* name) 
	{
		((void(*)(void* self, const char* name))g_hammer_nativeFunctions[189])(m_pSelf, name);
	}
	inline int GetParent() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[190])(m_pSelf);
	}
	inline void SetParent(CMapNode* parent) 
	{
		((void(*)(void* self, CMapNode* parent))g_hammer_nativeFunctions[191])(m_pSelf, parent);
	}
	inline int GetParentWorld() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[192])(m_pSelf);
	}
	inline int GetRootDocument(int64 nDocumentLoaded) 
	{
		return
		((int(*)(void* self, int64 nDocumentLoaded))g_hammer_nativeFunctions[193])(m_pSelf, nDocumentLoaded);
	}
	inline const char* GetDescription() 
	{
		return
		((const char*(*)(void* __self))g_hammer_nativeFunctions[194])(m_pSelf);
	}
	inline const char* GetTypeString() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[195])(m_pSelf);
	}
	inline int Copy() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[196])(m_pSelf);
	}
	inline int IsVisible() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[197])(m_pSelf);
	}
	inline void SetVisible(int bVisible) 
	{
		((void(*)(void* self, int bVisible))g_hammer_nativeFunctions[198])(m_pSelf, bVisible);
	}
	inline int IsSelected() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[199])(m_pSelf);
	}
	inline int GetChildCount() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[200])(m_pSelf);
	}
	inline int GetChild(int i) 
	{
		return
		((int(*)(void* self, int i))g_hammer_nativeFunctions[201])(m_pSelf, i);
	}
	inline int GetFirstDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[202])(m_pSelf, pos);
	}
	inline int GetNextDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[203])(m_pSelf, pos);
	}
	inline int AsMapEntity() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[204])(m_pSelf);
	}
	inline Vector GetOrigin() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[205])(m_pSelf);
	}
	inline QAngle GetAngles() 
	{
		return
		((QAngle(*)(void* self))g_hammer_nativeFunctions[206])(m_pSelf);
	}
	inline Vector GetScales() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[207])(m_pSelf);
	}
	inline void SetOrigin(Vector origin) 
	{
		((void(*)(void* self, Vector origin))g_hammer_nativeFunctions[208])(m_pSelf, origin);
	}
	inline void SetAngles(QAngle angles) 
	{
		((void(*)(void* self, QAngle angles))g_hammer_nativeFunctions[209])(m_pSelf, angles);
	}
	inline void SetScales(Vector scales) 
	{
		((void(*)(void* self, Vector scales))g_hammer_nativeFunctions[210])(m_pSelf, scales);
	}
	inline void BeginTransformOperation(int64 nTransformType, int64 nFlags) 
	{
		((void(*)(void* self, int64 nTransformType, int64 nFlags))g_hammer_nativeFunctions[211])(m_pSelf, nTransformType, nFlags);
	}
	inline void Transform(VMatrix matrix, int64 nFlags) 
	{
		((void(*)(void* self, VMatrix matrix, int64 nFlags))g_hammer_nativeFunctions[212])(m_pSelf, matrix, nFlags);
	}
	inline void EndTransformOperation() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[213])(m_pSelf);
	}
	inline void MarkBoundsDirty() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[214])(m_pSelf);
	}
	inline void FullBoundsUpdate() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[215])(m_pSelf);
	}
	inline void SetModifiedFlag() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[216])(m_pSelf);
	}
	inline int GeneratesEntityModelGeometry() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[217])(m_pSelf);
	}
	inline void DescriptionChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[218])(m_pSelf);
	}
	inline void CoreAttributeChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[219])(m_pSelf);
	}
};
class CMapNode
{
	public:
	void *m_pSelf;
	inline operator CMapNode*()
	{
		return (CMapNode*)m_pSelf;
	}
	inline int GetNodeID() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[220])(m_pSelf);
	}
	inline const char* GetName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[221])(m_pSelf);
	}
	inline void SetName(const char* name) 
	{
		((void(*)(void* self, const char* name))g_hammer_nativeFunctions[222])(m_pSelf, name);
	}
	inline int GetParent() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[223])(m_pSelf);
	}
	inline void SetParent(CMapNode* parent) 
	{
		((void(*)(void* self, CMapNode* parent))g_hammer_nativeFunctions[224])(m_pSelf, parent);
	}
	inline int GetParentWorld() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[225])(m_pSelf);
	}
	inline int GetRootDocument(int64 nDocumentLoaded) 
	{
		return
		((int(*)(void* self, int64 nDocumentLoaded))g_hammer_nativeFunctions[226])(m_pSelf, nDocumentLoaded);
	}
	inline const char* GetDescription() 
	{
		return
		((const char*(*)(void* __self))g_hammer_nativeFunctions[227])(m_pSelf);
	}
	inline const char* GetTypeString() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[228])(m_pSelf);
	}
	inline int Copy() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[229])(m_pSelf);
	}
	inline int IsVisible() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[230])(m_pSelf);
	}
	inline void SetVisible(int bVisible) 
	{
		((void(*)(void* self, int bVisible))g_hammer_nativeFunctions[231])(m_pSelf, bVisible);
	}
	inline int IsSelected() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[232])(m_pSelf);
	}
	inline int GetChildCount() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[233])(m_pSelf);
	}
	inline int GetChild(int i) 
	{
		return
		((int(*)(void* self, int i))g_hammer_nativeFunctions[234])(m_pSelf, i);
	}
	inline int GetFirstDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[235])(m_pSelf, pos);
	}
	inline int GetNextDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[236])(m_pSelf, pos);
	}
	inline int AsMapEntity() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[237])(m_pSelf);
	}
	inline Vector GetOrigin() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[238])(m_pSelf);
	}
	inline QAngle GetAngles() 
	{
		return
		((QAngle(*)(void* self))g_hammer_nativeFunctions[239])(m_pSelf);
	}
	inline Vector GetScales() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[240])(m_pSelf);
	}
	inline void SetOrigin(Vector origin) 
	{
		((void(*)(void* self, Vector origin))g_hammer_nativeFunctions[241])(m_pSelf, origin);
	}
	inline void SetAngles(QAngle angles) 
	{
		((void(*)(void* self, QAngle angles))g_hammer_nativeFunctions[242])(m_pSelf, angles);
	}
	inline void SetScales(Vector scales) 
	{
		((void(*)(void* self, Vector scales))g_hammer_nativeFunctions[243])(m_pSelf, scales);
	}
	inline void BeginTransformOperation(int64 nTransformType, int64 nFlags) 
	{
		((void(*)(void* self, int64 nTransformType, int64 nFlags))g_hammer_nativeFunctions[244])(m_pSelf, nTransformType, nFlags);
	}
	inline void Transform(VMatrix matrix, int64 nFlags) 
	{
		((void(*)(void* self, VMatrix matrix, int64 nFlags))g_hammer_nativeFunctions[245])(m_pSelf, matrix, nFlags);
	}
	inline void EndTransformOperation() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[246])(m_pSelf);
	}
	inline void MarkBoundsDirty() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[247])(m_pSelf);
	}
	inline void FullBoundsUpdate() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[248])(m_pSelf);
	}
	inline void SetModifiedFlag() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[249])(m_pSelf);
	}
	inline int GeneratesEntityModelGeometry() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[250])(m_pSelf);
	}
	inline void DescriptionChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[251])(m_pSelf);
	}
	inline void CoreAttributeChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[252])(m_pSelf);
	}
};
class CMapPath
{
	public:
	void *m_pSelf;
	inline operator CMapPath*()
	{
		return (CMapPath*)m_pSelf;
	}
	//NativeMapDoc.CMapPath.__N.From_CMapEntity_To_CMapPath = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[253];
	//NativeMapDoc.CMapPath.__N.To_CMapEntity_From_CMapPath = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[254];
	//NativeMapDoc.CMapPath.__N.From_CMapNode_To_CMapPath = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[255];
	//NativeMapDoc.CMapPath.__N.To_CMapNode_From_CMapPath = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[256];
	inline int AddNewNodeToPath() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[257])(m_pSelf);
	}
	inline const char* GetClassName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[258])(m_pSelf);
	}
	inline void SetClass(const char* classname) 
	{
		((void(*)(void* self, const char* classname))g_hammer_nativeFunctions[259])(m_pSelf, classname);
	}
	inline void SetKeyValue(const char* key, const char* value) 
	{
		((void(*)(void* self, const char* key, const char* value))g_hammer_nativeFunctions[260])(m_pSelf, key, value);
	}
	inline const char* GetKeyValue(const char* key) 
	{
		return
		((const char*(*)(void* self, const char* key))g_hammer_nativeFunctions[261])(m_pSelf, key);
	}
	inline int TargetNameMatches(const char* name) 
	{
		return
		((int(*)(void* self, const char* name))g_hammer_nativeFunctions[262])(m_pSelf, name);
	}
	inline void SetDefaultBounds(Vector minBounds, Vector maxBounds) 
	{
		((void(*)(void* __self, Vector __minBounds, Vector __maxBounds))g_hammer_nativeFunctions[263])(m_pSelf, minBounds, maxBounds);
	}
	inline int GetNodeID() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[264])(m_pSelf);
	}
	inline const char* GetName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[265])(m_pSelf);
	}
	inline void SetName(const char* name) 
	{
		((void(*)(void* self, const char* name))g_hammer_nativeFunctions[266])(m_pSelf, name);
	}
	inline int GetParent() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[267])(m_pSelf);
	}
	inline void SetParent(CMapNode* parent) 
	{
		((void(*)(void* self, CMapNode* parent))g_hammer_nativeFunctions[268])(m_pSelf, parent);
	}
	inline int GetParentWorld() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[269])(m_pSelf);
	}
	inline int GetRootDocument(int64 nDocumentLoaded) 
	{
		return
		((int(*)(void* self, int64 nDocumentLoaded))g_hammer_nativeFunctions[270])(m_pSelf, nDocumentLoaded);
	}
	inline const char* GetDescription() 
	{
		return
		((const char*(*)(void* __self))g_hammer_nativeFunctions[271])(m_pSelf);
	}
	inline const char* GetTypeString() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[272])(m_pSelf);
	}
	inline int Copy() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[273])(m_pSelf);
	}
	inline int IsVisible() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[274])(m_pSelf);
	}
	inline void SetVisible(int bVisible) 
	{
		((void(*)(void* self, int bVisible))g_hammer_nativeFunctions[275])(m_pSelf, bVisible);
	}
	inline int IsSelected() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[276])(m_pSelf);
	}
	inline int GetChildCount() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[277])(m_pSelf);
	}
	inline int GetChild(int i) 
	{
		return
		((int(*)(void* self, int i))g_hammer_nativeFunctions[278])(m_pSelf, i);
	}
	inline int GetFirstDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[279])(m_pSelf, pos);
	}
	inline int GetNextDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[280])(m_pSelf, pos);
	}
	inline int AsMapEntity() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[281])(m_pSelf);
	}
	inline Vector GetOrigin() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[282])(m_pSelf);
	}
	inline QAngle GetAngles() 
	{
		return
		((QAngle(*)(void* self))g_hammer_nativeFunctions[283])(m_pSelf);
	}
	inline Vector GetScales() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[284])(m_pSelf);
	}
	inline void SetOrigin(Vector origin) 
	{
		((void(*)(void* self, Vector origin))g_hammer_nativeFunctions[285])(m_pSelf, origin);
	}
	inline void SetAngles(QAngle angles) 
	{
		((void(*)(void* self, QAngle angles))g_hammer_nativeFunctions[286])(m_pSelf, angles);
	}
	inline void SetScales(Vector scales) 
	{
		((void(*)(void* self, Vector scales))g_hammer_nativeFunctions[287])(m_pSelf, scales);
	}
	inline void BeginTransformOperation(int64 nTransformType, int64 nFlags) 
	{
		((void(*)(void* self, int64 nTransformType, int64 nFlags))g_hammer_nativeFunctions[288])(m_pSelf, nTransformType, nFlags);
	}
	inline void Transform(VMatrix matrix, int64 nFlags) 
	{
		((void(*)(void* self, VMatrix matrix, int64 nFlags))g_hammer_nativeFunctions[289])(m_pSelf, matrix, nFlags);
	}
	inline void EndTransformOperation() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[290])(m_pSelf);
	}
	inline void MarkBoundsDirty() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[291])(m_pSelf);
	}
	inline void FullBoundsUpdate() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[292])(m_pSelf);
	}
	inline void SetModifiedFlag() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[293])(m_pSelf);
	}
	inline int GeneratesEntityModelGeometry() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[294])(m_pSelf);
	}
	inline void DescriptionChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[295])(m_pSelf);
	}
	inline void CoreAttributeChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[296])(m_pSelf);
	}
};
class CMapPathNode
{
	public:
	void *m_pSelf;
	inline operator CMapPathNode*()
	{
		return (CMapPathNode*)m_pSelf;
	}
	//NativeMapDoc.CMapPathNode.__N.From_CMapEntity_To_CMapPathNode = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[297];
	//NativeMapDoc.CMapPathNode.__N.To_CMapEntity_From_CMapPathNode = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[298];
	//NativeMapDoc.CMapPathNode.__N.From_CMapNode_To_CMapPathNode = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[299];
	//NativeMapDoc.CMapPathNode.__N.To_CMapNode_From_CMapPathNode = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[300];
	inline const char* GetClassName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[301])(m_pSelf);
	}
	inline void SetClass(const char* classname) 
	{
		((void(*)(void* self, const char* classname))g_hammer_nativeFunctions[302])(m_pSelf, classname);
	}
	inline void SetKeyValue(const char* key, const char* value) 
	{
		((void(*)(void* self, const char* key, const char* value))g_hammer_nativeFunctions[303])(m_pSelf, key, value);
	}
	inline const char* GetKeyValue(const char* key) 
	{
		return
		((const char*(*)(void* self, const char* key))g_hammer_nativeFunctions[304])(m_pSelf, key);
	}
	inline int TargetNameMatches(const char* name) 
	{
		return
		((int(*)(void* self, const char* name))g_hammer_nativeFunctions[305])(m_pSelf, name);
	}
	inline void SetDefaultBounds(Vector minBounds, Vector maxBounds) 
	{
		((void(*)(void* __self, Vector __minBounds, Vector __maxBounds))g_hammer_nativeFunctions[306])(m_pSelf, minBounds, maxBounds);
	}
	inline int GetNodeID() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[307])(m_pSelf);
	}
	inline const char* GetName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[308])(m_pSelf);
	}
	inline void SetName(const char* name) 
	{
		((void(*)(void* self, const char* name))g_hammer_nativeFunctions[309])(m_pSelf, name);
	}
	inline int GetParent() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[310])(m_pSelf);
	}
	inline void SetParent(CMapNode* parent) 
	{
		((void(*)(void* self, CMapNode* parent))g_hammer_nativeFunctions[311])(m_pSelf, parent);
	}
	inline int GetParentWorld() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[312])(m_pSelf);
	}
	inline int GetRootDocument(int64 nDocumentLoaded) 
	{
		return
		((int(*)(void* self, int64 nDocumentLoaded))g_hammer_nativeFunctions[313])(m_pSelf, nDocumentLoaded);
	}
	inline const char* GetDescription() 
	{
		return
		((const char*(*)(void* __self))g_hammer_nativeFunctions[314])(m_pSelf);
	}
	inline const char* GetTypeString() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[315])(m_pSelf);
	}
	inline int Copy() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[316])(m_pSelf);
	}
	inline int IsVisible() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[317])(m_pSelf);
	}
	inline void SetVisible(int bVisible) 
	{
		((void(*)(void* self, int bVisible))g_hammer_nativeFunctions[318])(m_pSelf, bVisible);
	}
	inline int IsSelected() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[319])(m_pSelf);
	}
	inline int GetChildCount() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[320])(m_pSelf);
	}
	inline int GetChild(int i) 
	{
		return
		((int(*)(void* self, int i))g_hammer_nativeFunctions[321])(m_pSelf, i);
	}
	inline int GetFirstDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[322])(m_pSelf, pos);
	}
	inline int GetNextDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[323])(m_pSelf, pos);
	}
	inline int AsMapEntity() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[324])(m_pSelf);
	}
	inline Vector GetOrigin() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[325])(m_pSelf);
	}
	inline QAngle GetAngles() 
	{
		return
		((QAngle(*)(void* self))g_hammer_nativeFunctions[326])(m_pSelf);
	}
	inline Vector GetScales() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[327])(m_pSelf);
	}
	inline void SetOrigin(Vector origin) 
	{
		((void(*)(void* self, Vector origin))g_hammer_nativeFunctions[328])(m_pSelf, origin);
	}
	inline void SetAngles(QAngle angles) 
	{
		((void(*)(void* self, QAngle angles))g_hammer_nativeFunctions[329])(m_pSelf, angles);
	}
	inline void SetScales(Vector scales) 
	{
		((void(*)(void* self, Vector scales))g_hammer_nativeFunctions[330])(m_pSelf, scales);
	}
	inline void BeginTransformOperation(int64 nTransformType, int64 nFlags) 
	{
		((void(*)(void* self, int64 nTransformType, int64 nFlags))g_hammer_nativeFunctions[331])(m_pSelf, nTransformType, nFlags);
	}
	inline void Transform(VMatrix matrix, int64 nFlags) 
	{
		((void(*)(void* self, VMatrix matrix, int64 nFlags))g_hammer_nativeFunctions[332])(m_pSelf, matrix, nFlags);
	}
	inline void EndTransformOperation() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[333])(m_pSelf);
	}
	inline void MarkBoundsDirty() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[334])(m_pSelf);
	}
	inline void FullBoundsUpdate() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[335])(m_pSelf);
	}
	inline void SetModifiedFlag() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[336])(m_pSelf);
	}
	inline int GeneratesEntityModelGeometry() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[337])(m_pSelf);
	}
	inline void DescriptionChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[338])(m_pSelf);
	}
	inline void CoreAttributeChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[339])(m_pSelf);
	}
};
class CMapStaticOverlay
{
	public:
	void *m_pSelf;
	inline operator CMapStaticOverlay*()
	{
		return (CMapStaticOverlay*)m_pSelf;
	}
	//NativeMapDoc.CMapStaticOverlay.__N.From_CMapMesh_To_CMapStaticOverlay = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[340];
	//NativeMapDoc.CMapStaticOverlay.__N.To_CMapMesh_From_CMapStaticOverlay = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[341];
	//NativeMapDoc.CMapStaticOverlay.__N.From_CMapNode_To_CMapStaticOverlay = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[342];
	//NativeMapDoc.CMapStaticOverlay.__N.To_CMapNode_From_CMapStaticOverlay = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[343];
	inline void CreateCenteredQuad(float flWidth, float flHeight, const char* pMaterialName) 
	{
		((void(*)(void* self, float flWidth, float flHeight, const char* pMaterialName))g_hammer_nativeFunctions[344])(m_pSelf, flWidth, flHeight, pMaterialName);
	}
	inline void AssignMaterialToMesh(const char* materialName) 
	{
		((void(*)(void* self, const char* materialName))g_hammer_nativeFunctions[345])(m_pSelf, materialName);
	}
	inline void ConstructFromData(int numVerticies, void* vertexPositions, void* vertexTexCoords, int numIndices, void* vertexIndices, int numFaces, void* faceVertexCounts, void* faceMaterialsPtr, int mergeVertices, float vertexMergeTolerance) 
	{
		((void(*)(void* self, int numVerticies, void* vertexPositions, void* vertexTexCoords, int numIndices, void* vertexIndices, int numFaces, void* faceVertexCounts, void* faceMaterialsPtr, int mergeVertices, float vertexMergeTolerance))g_hammer_nativeFunctions[346])(m_pSelf, numVerticies, vertexPositions, vertexTexCoords, numIndices, vertexIndices, numFaces, faceVertexCounts, faceMaterialsPtr, mergeVertices, vertexMergeTolerance);
	}
	inline void GetFaceMaterials(CUtlVector<CUtlString>* materials) 
	{
		((void(*)(void* __self, CUtlVector<CUtlString>* __materials))g_hammer_nativeFunctions[347])(m_pSelf, materials);
	}
	inline int GetNodeID() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[348])(m_pSelf);
	}
	inline const char* GetName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[349])(m_pSelf);
	}
	inline void SetName(const char* name) 
	{
		((void(*)(void* self, const char* name))g_hammer_nativeFunctions[350])(m_pSelf, name);
	}
	inline int GetParent() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[351])(m_pSelf);
	}
	inline void SetParent(CMapNode* parent) 
	{
		((void(*)(void* self, CMapNode* parent))g_hammer_nativeFunctions[352])(m_pSelf, parent);
	}
	inline int GetParentWorld() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[353])(m_pSelf);
	}
	inline int GetRootDocument(int64 nDocumentLoaded) 
	{
		return
		((int(*)(void* self, int64 nDocumentLoaded))g_hammer_nativeFunctions[354])(m_pSelf, nDocumentLoaded);
	}
	inline const char* GetDescription() 
	{
		return
		((const char*(*)(void* __self))g_hammer_nativeFunctions[355])(m_pSelf);
	}
	inline const char* GetTypeString() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[356])(m_pSelf);
	}
	inline int Copy() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[357])(m_pSelf);
	}
	inline int IsVisible() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[358])(m_pSelf);
	}
	inline void SetVisible(int bVisible) 
	{
		((void(*)(void* self, int bVisible))g_hammer_nativeFunctions[359])(m_pSelf, bVisible);
	}
	inline int IsSelected() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[360])(m_pSelf);
	}
	inline int GetChildCount() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[361])(m_pSelf);
	}
	inline int GetChild(int i) 
	{
		return
		((int(*)(void* self, int i))g_hammer_nativeFunctions[362])(m_pSelf, i);
	}
	inline int GetFirstDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[363])(m_pSelf, pos);
	}
	inline int GetNextDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[364])(m_pSelf, pos);
	}
	inline int AsMapEntity() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[365])(m_pSelf);
	}
	inline Vector GetOrigin() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[366])(m_pSelf);
	}
	inline QAngle GetAngles() 
	{
		return
		((QAngle(*)(void* self))g_hammer_nativeFunctions[367])(m_pSelf);
	}
	inline Vector GetScales() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[368])(m_pSelf);
	}
	inline void SetOrigin(Vector origin) 
	{
		((void(*)(void* self, Vector origin))g_hammer_nativeFunctions[369])(m_pSelf, origin);
	}
	inline void SetAngles(QAngle angles) 
	{
		((void(*)(void* self, QAngle angles))g_hammer_nativeFunctions[370])(m_pSelf, angles);
	}
	inline void SetScales(Vector scales) 
	{
		((void(*)(void* self, Vector scales))g_hammer_nativeFunctions[371])(m_pSelf, scales);
	}
	inline void BeginTransformOperation(int64 nTransformType, int64 nFlags) 
	{
		((void(*)(void* self, int64 nTransformType, int64 nFlags))g_hammer_nativeFunctions[372])(m_pSelf, nTransformType, nFlags);
	}
	inline void Transform(VMatrix matrix, int64 nFlags) 
	{
		((void(*)(void* self, VMatrix matrix, int64 nFlags))g_hammer_nativeFunctions[373])(m_pSelf, matrix, nFlags);
	}
	inline void EndTransformOperation() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[374])(m_pSelf);
	}
	inline void MarkBoundsDirty() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[375])(m_pSelf);
	}
	inline void FullBoundsUpdate() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[376])(m_pSelf);
	}
	inline void SetModifiedFlag() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[377])(m_pSelf);
	}
	inline int GeneratesEntityModelGeometry() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[378])(m_pSelf);
	}
	inline void DescriptionChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[379])(m_pSelf);
	}
	inline void CoreAttributeChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[380])(m_pSelf);
	}
};
class CMapView
{
	public:
	void *m_pSelf;
	inline operator CMapView*()
	{
		return (CMapView*)m_pSelf;
	}
	inline int GetMapDoc() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[381])(m_pSelf);
	}
	inline void MarkHudDirty() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[382])(m_pSelf);
	}
	inline const CToolCamera* GetCamera() 
	{
		return
		((const CToolCamera*(*)(void* self))g_hammer_nativeFunctions[383])(m_pSelf);
	}
	inline int IsActive() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[384])(m_pSelf);
	}
	inline void GetMousePosition(Vector2D* pos) 
	{
		((void(*)(void* __self, Vector2D* __pos))g_hammer_nativeFunctions[385])(m_pSelf, pos);
	}
	inline void EnterFreeDragMode(Vector2D vClientPos, CMapNode* pObjectToSelect, Vector vecInitialHitNormal, int bAlignToSurface) 
	{
		((void(*)(void* self, Vector2D vClientPos, CMapNode* pObjectToSelect, Vector vecInitialHitNormal, int bAlignToSurface))g_hammer_nativeFunctions[386])(m_pSelf, vClientPos, pObjectToSelect, vecInitialHitNormal, bAlignToSurface);
	}
	inline void UpdateFreeDragMode(Vector2D vClientPos, int bModifyAlignToSurface) 
	{
		((void(*)(void* self, Vector2D vClientPos, int bModifyAlignToSurface))g_hammer_nativeFunctions[387])(m_pSelf, vClientPos, bModifyAlignToSurface);
	}
	inline void ExitFreeDragMode(int bRestoreToolState) 
	{
		((void(*)(void* self, int bRestoreToolState))g_hammer_nativeFunctions[388])(m_pSelf, bRestoreToolState);
	}
	inline void GetDropTarget(Vector* pVecNormalOut, Vector* pVecDropPointOut, Vector2D vecPoint2D) 
	{
		((void(*)(void* __self, Vector* __pVecNormalOut, Vector* __pVecDropPointOut, Vector2D __vecPoint2D))g_hammer_nativeFunctions[389])(m_pSelf, pVecNormalOut, pVecDropPointOut, vecPoint2D);
	}
	inline void UpdateManagedGizmoState(int isHoveredOverSomething, float distanceFromCamera) 
	{
		((void(*)(void* self, int isHoveredOverSomething, float distanceFromCamera))g_hammer_nativeFunctions[390])(m_pSelf, isHoveredOverSomething, distanceFromCamera);
	}
	inline int64 GetManipulationMode() 
	{
		return
		((int64(*)(void* __self))g_hammer_nativeFunctions[391])(m_pSelf);
	}
	inline float HitDistanceAtMouse() 
	{
		return
		((float(*)(void* __self))g_hammer_nativeFunctions[392])(m_pSelf);
	}
};
class CMapWorld
{
	public:
	void *m_pSelf;
	inline operator CMapWorld*()
	{
		return (CMapWorld*)m_pSelf;
	}
	//NativeMapDoc.CMapWorld.__N.From_CMapNode_To_CMapWorld = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[393];
	//NativeMapDoc.CMapWorld.__N.To_CMapNode_From_CMapWorld = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[394];
	inline void SetSerializedScene(const char* json) 
	{
		((void(*)(void* self, const char* json))g_hammer_nativeFunctions[395])(m_pSelf, json);
	}
	inline const char* GetSerializedScene() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[396])(m_pSelf);
	}
	inline int FindNodeByID(int nodeId) 
	{
		return
		((int(*)(void* self, int nodeId))g_hammer_nativeFunctions[397])(m_pSelf, nodeId);
	}
	inline int FindEntityByNodeId(int nodeId) 
	{
		return
		((int(*)(void* __self, int __nodeId))g_hammer_nativeFunctions[398])(m_pSelf, nodeId);
	}
	inline Trace::TraceResult Trace(Trace::TraceRequest traceRequest) 
	{
		return
		((Trace::TraceResult(*)(void* __self, Trace::TraceRequest __traceRequest))g_hammer_nativeFunctions[399])(m_pSelf, traceRequest);
	}
	inline int GetNodeID() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[400])(m_pSelf);
	}
	inline const char* GetName() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[401])(m_pSelf);
	}
	inline void SetName(const char* name) 
	{
		((void(*)(void* self, const char* name))g_hammer_nativeFunctions[402])(m_pSelf, name);
	}
	inline int GetParent() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[403])(m_pSelf);
	}
	inline void SetParent(CMapNode* parent) 
	{
		((void(*)(void* self, CMapNode* parent))g_hammer_nativeFunctions[404])(m_pSelf, parent);
	}
	inline int GetParentWorld() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[405])(m_pSelf);
	}
	inline int GetRootDocument(int64 nDocumentLoaded) 
	{
		return
		((int(*)(void* self, int64 nDocumentLoaded))g_hammer_nativeFunctions[406])(m_pSelf, nDocumentLoaded);
	}
	inline const char* GetDescription() 
	{
		return
		((const char*(*)(void* __self))g_hammer_nativeFunctions[407])(m_pSelf);
	}
	inline const char* GetTypeString() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[408])(m_pSelf);
	}
	inline int Copy() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[409])(m_pSelf);
	}
	inline int IsVisible() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[410])(m_pSelf);
	}
	inline void SetVisible(int bVisible) 
	{
		((void(*)(void* self, int bVisible))g_hammer_nativeFunctions[411])(m_pSelf, bVisible);
	}
	inline int IsSelected() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[412])(m_pSelf);
	}
	inline int GetChildCount() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[413])(m_pSelf);
	}
	inline int GetChild(int i) 
	{
		return
		((int(*)(void* self, int i))g_hammer_nativeFunctions[414])(m_pSelf, i);
	}
	inline int GetFirstDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[415])(m_pSelf, pos);
	}
	inline int GetNextDescendent(EnumChildrenPos_t* pos) 
	{
		return
		((int(*)(void* __self, EnumChildrenPos_t* __pos))g_hammer_nativeFunctions[416])(m_pSelf, pos);
	}
	inline int AsMapEntity() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[417])(m_pSelf);
	}
	inline Vector GetOrigin() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[418])(m_pSelf);
	}
	inline QAngle GetAngles() 
	{
		return
		((QAngle(*)(void* self))g_hammer_nativeFunctions[419])(m_pSelf);
	}
	inline Vector GetScales() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[420])(m_pSelf);
	}
	inline void SetOrigin(Vector origin) 
	{
		((void(*)(void* self, Vector origin))g_hammer_nativeFunctions[421])(m_pSelf, origin);
	}
	inline void SetAngles(QAngle angles) 
	{
		((void(*)(void* self, QAngle angles))g_hammer_nativeFunctions[422])(m_pSelf, angles);
	}
	inline void SetScales(Vector scales) 
	{
		((void(*)(void* self, Vector scales))g_hammer_nativeFunctions[423])(m_pSelf, scales);
	}
	inline void BeginTransformOperation(int64 nTransformType, int64 nFlags) 
	{
		((void(*)(void* self, int64 nTransformType, int64 nFlags))g_hammer_nativeFunctions[424])(m_pSelf, nTransformType, nFlags);
	}
	inline void Transform(VMatrix matrix, int64 nFlags) 
	{
		((void(*)(void* self, VMatrix matrix, int64 nFlags))g_hammer_nativeFunctions[425])(m_pSelf, matrix, nFlags);
	}
	inline void EndTransformOperation() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[426])(m_pSelf);
	}
	inline void MarkBoundsDirty() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[427])(m_pSelf);
	}
	inline void FullBoundsUpdate() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[428])(m_pSelf);
	}
	inline void SetModifiedFlag() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[429])(m_pSelf);
	}
	inline int GeneratesEntityModelGeometry() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[430])(m_pSelf);
	}
	inline void DescriptionChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[431])(m_pSelf);
	}
	inline void CoreAttributeChanged() 
	{
		((void(*)(void* __self))g_hammer_nativeFunctions[432])(m_pSelf);
	}
};
class CQHammerMainWnd
{
	public:
	void *m_pSelf;
	inline operator CQHammerMainWnd*()
	{
		return (CQHammerMainWnd*)m_pSelf;
	}
	//Native.CQHammerMainWnd.__N.From_CFramelessMainWindow_To_CQHammerMainWnd = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[433];
	//Native.CQHammerMainWnd.__N.To_CFramelessMainWindow_From_CQHammerMainWnd = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[434];
	//Native.CQHammerMainWnd.__N.From_QMainWindow_To_CQHammerMainWnd = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[435];
	//Native.CQHammerMainWnd.__N.To_QMainWindow_From_CQHammerMainWnd = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[436];
	//Native.CQHammerMainWnd.__N.From_QWidget_To_CQHammerMainWnd = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[437];
	//Native.CQHammerMainWnd.__N.To_QWidget_From_CQHammerMainWnd = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[438];
	//Native.CQHammerMainWnd.__N.From_QObject_To_CQHammerMainWnd = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[439];
	//Native.CQHammerMainWnd.__N.To_QObject_From_CQHammerMainWnd = (delegate* unmanaged[SuppressGCTransition]< IntPtr, IntPtr >) nativeFunctions[440];
	inline void CreateEverything() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[441])(m_pSelf);
	}
	inline void CreateMenus() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[442])(m_pSelf);
	}
	inline void SetupDefaultLayout() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[443])(m_pSelf);
	}
	inline void SetTitleBarWidgets(QPushButton* icon, QLabel* titleLabel, QMenuBar* menuBar, QWidget* grabber, QWidget* minimizeButton, QWidget* maximizeButton, QWidget* closeButton) 
	{
		((void(*)(void* self, QPushButton* icon, QLabel* titleLabel, QMenuBar* menuBar, QWidget* grabber, QWidget* minimizeButton, QWidget* maximizeButton, QWidget* closeButton))g_hammer_nativeFunctions[444])(m_pSelf, icon, titleLabel, menuBar, grabber, minimizeButton, maximizeButton, closeButton);
	}
	inline Vector iconSize() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[445])(m_pSelf);
	}
	inline void setIconSize(Vector iconSize) 
	{
		((void(*)(void* self, Vector iconSize))g_hammer_nativeFunctions[446])(m_pSelf, iconSize);
	}
	inline const QMenuBar* menuBar() 
	{
		return
		((const QMenuBar*(*)(void* self))g_hammer_nativeFunctions[447])(m_pSelf);
	}
	inline void setMenuBar(QMenuBar* menubar) 
	{
		((void(*)(void* self, QMenuBar* menubar))g_hammer_nativeFunctions[448])(m_pSelf, menubar);
	}
	inline void setMenuWidget(QWidget* menubar) 
	{
		((void(*)(void* self, QWidget* menubar))g_hammer_nativeFunctions[449])(m_pSelf, menubar);
	}
	inline const QStatusBar* statusBar() 
	{
		return
		((const QStatusBar*(*)(void* self))g_hammer_nativeFunctions[450])(m_pSelf);
	}
	inline void setStatusBar(QStatusBar* statusbar) 
	{
		((void(*)(void* self, QStatusBar* statusbar))g_hammer_nativeFunctions[451])(m_pSelf, statusbar);
	}
	inline const QWidget* centralWidget() 
	{
		return
		((const QWidget*(*)(void* self))g_hammer_nativeFunctions[452])(m_pSelf);
	}
	inline void setCentralWidget(QWidget* widget) 
	{
		((void(*)(void* self, QWidget* widget))g_hammer_nativeFunctions[453])(m_pSelf, widget);
	}
	inline int isAnimated() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[454])(m_pSelf);
	}
	inline void setAnimated(int enabled) 
	{
		((void(*)(void* self, int enabled))g_hammer_nativeFunctions[455])(m_pSelf, enabled);
	}
	inline void addToolBarBreak(int64 area) 
	{
		((void(*)(void* self, int64 area))g_hammer_nativeFunctions[456])(m_pSelf, area);
	}
	inline void insertToolBarBreak(QToolBar* before) 
	{
		((void(*)(void* self, QToolBar* before))g_hammer_nativeFunctions[457])(m_pSelf, before);
	}
	inline void addToolBar(int64 area, QToolBar* toolbar) 
	{
		((void(*)(void* self, int64 area, QToolBar* toolbar))g_hammer_nativeFunctions[458])(m_pSelf, area, toolbar);
	}
	inline void addToolBar(QToolBar* toolbar) 
	{
		((void(*)(void* self, QToolBar* toolbar))g_hammer_nativeFunctions[459])(m_pSelf, toolbar);
	}
	inline void insertToolBar(QToolBar* before, QToolBar* toolbar) 
	{
		((void(*)(void* self, QToolBar* before, QToolBar* toolbar))g_hammer_nativeFunctions[460])(m_pSelf, before, toolbar);
	}
	inline void removeToolBar(QToolBar* toolbar) 
	{
		((void(*)(void* self, QToolBar* toolbar))g_hammer_nativeFunctions[461])(m_pSelf, toolbar);
	}
	inline void removeToolBarBreak(QToolBar* before) 
	{
		((void(*)(void* self, QToolBar* before))g_hammer_nativeFunctions[462])(m_pSelf, before);
	}
	inline const char* saveState(int version) 
	{
		return
		((const char*(*)(void* self, int version))g_hammer_nativeFunctions[463])(m_pSelf, version);
	}
	inline int restoreState(const char* state) 
	{
		return
		((int(*)(void* self, const char* state))g_hammer_nativeFunctions[464])(m_pSelf, state);
	}
	inline int isTopLevel() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[465])(m_pSelf);
	}
	inline int isWindow() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[466])(m_pSelf);
	}
	inline int isModal() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[467])(m_pSelf);
	}
	inline void setStyleSheet(const QChar * sheet) 
	{
		((void(*)(void* self, const QChar * sheet))g_hammer_nativeFunctions[468])(m_pSelf, sheet);
	}
	inline const QChar * windowTitle() 
	{
		return
		((const QChar *(*)(void* self))g_hammer_nativeFunctions[469])(m_pSelf);
	}
	inline void setWindowTitle(const QChar * title) 
	{
		((void(*)(void* self, const QChar * title))g_hammer_nativeFunctions[470])(m_pSelf, title);
	}
	inline void setWindowFlags(int64 type) 
	{
		((void(*)(void* self, int64 type))g_hammer_nativeFunctions[471])(m_pSelf, type);
	}
	inline int64 windowFlags() 
	{
		return
		((int64(*)(void* self))g_hammer_nativeFunctions[472])(m_pSelf);
	}
	inline Vector size() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[473])(m_pSelf);
	}
	inline void resize(Vector x) 
	{
		((void(*)(void* self, Vector x))g_hammer_nativeFunctions[474])(m_pSelf, x);
	}
	inline Vector minimumSize() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[475])(m_pSelf);
	}
	inline void setMinimumSize(Vector x) 
	{
		((void(*)(void* self, Vector x))g_hammer_nativeFunctions[476])(m_pSelf, x);
	}
	inline Vector maximumSize() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[477])(m_pSelf);
	}
	inline void setMaximumSize(Vector x) 
	{
		((void(*)(void* self, Vector x))g_hammer_nativeFunctions[478])(m_pSelf, x);
	}
	inline Vector sizeHint() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[479])(m_pSelf);
	}
	inline Vector pos() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[480])(m_pSelf);
	}
	inline void move(Vector x) 
	{
		((void(*)(void* self, Vector x))g_hammer_nativeFunctions[481])(m_pSelf, x);
	}
	inline int isEnabled() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[482])(m_pSelf);
	}
	inline void setEnabled(int x) 
	{
		((void(*)(void* self, int x))g_hammer_nativeFunctions[483])(m_pSelf, x);
	}
	inline void setVisible(int visible) 
	{
		((void(*)(void* self, int visible))g_hammer_nativeFunctions[484])(m_pSelf, visible);
	}
	inline void show() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[485])(m_pSelf);
	}
	inline void hide() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[486])(m_pSelf);
	}
	inline void showMinimized() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[487])(m_pSelf);
	}
	inline void showMaximized() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[488])(m_pSelf);
	}
	inline void showFullScreen() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[489])(m_pSelf);
	}
	inline void showNormal() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[490])(m_pSelf);
	}
	inline int close() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[491])(m_pSelf);
	}
	inline void raise() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[492])(m_pSelf);
	}
	inline void lower() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[493])(m_pSelf);
	}
	inline int isVisible() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[494])(m_pSelf);
	}
	inline int isHidden() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[495])(m_pSelf);
	}
	inline void setHidden(int b) 
	{
		((void(*)(void* self, int b))g_hammer_nativeFunctions[496])(m_pSelf, b);
	}
	inline void setAttribute(int64 a, int on) 
	{
		((void(*)(void* self, int64 a, int on))g_hammer_nativeFunctions[497])(m_pSelf, a, on);
	}
	inline int testAttribute(int64 a) 
	{
		return
		((int(*)(void* self, int64 a))g_hammer_nativeFunctions[498])(m_pSelf, a);
	}
	inline int acceptDrops() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[499])(m_pSelf);
	}
	inline void setAcceptDrops(int on) 
	{
		((void(*)(void* self, int on))g_hammer_nativeFunctions[500])(m_pSelf, on);
	}
	inline void updateGeometry() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[501])(m_pSelf);
	}
	inline void update() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[502])(m_pSelf);
	}
	inline void repaint() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[503])(m_pSelf);
	}
	inline void setCursor(int64 shape) 
	{
		((void(*)(void* self, int64 shape))g_hammer_nativeFunctions[504])(m_pSelf, shape);
	}
	inline void setCursor(QPixmap* pixmap) 
	{
		((void(*)(void* __self, QPixmap* __pixmap))g_hammer_nativeFunctions[505])(m_pSelf, pixmap);
	}
	inline void unsetCursor() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[506])(m_pSelf);
	}
	inline void setWindowIcon(const char* icon) 
	{
		((void(*)(void* self, const char* icon))g_hammer_nativeFunctions[507])(m_pSelf, icon);
	}
	inline void setWindowIconFromPixmap(QPixmap* icon) 
	{
		((void(*)(void* __self, QPixmap* __icon))g_hammer_nativeFunctions[508])(m_pSelf, icon);
	}
	inline void setWindowIconText(const QChar * str) 
	{
		((void(*)(void* self, const QChar * str))g_hammer_nativeFunctions[509])(m_pSelf, str);
	}
	inline void setWindowOpacity(float level) 
	{
		((void(*)(void* self, float level))g_hammer_nativeFunctions[510])(m_pSelf, level);
	}
	inline float windowOpacity() 
	{
		return
		((float(*)(void* self))g_hammer_nativeFunctions[511])(m_pSelf);
	}
	inline int isMinimized() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[512])(m_pSelf);
	}
	inline int isMaximized() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[513])(m_pSelf);
	}
	inline int isFullScreen() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[514])(m_pSelf);
	}
	inline void setMouseTracking(int enable) 
	{
		((void(*)(void* self, int enable))g_hammer_nativeFunctions[515])(m_pSelf, enable);
	}
	inline int hasMouseTracking() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[516])(m_pSelf);
	}
	inline int underMouse() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[517])(m_pSelf);
	}
	inline Vector mapToGlobal(Vector p) 
	{
		return
		((Vector(*)(void* self, Vector p))g_hammer_nativeFunctions[518])(m_pSelf, p);
	}
	inline Vector mapFromGlobal(Vector p) 
	{
		return
		((Vector(*)(void* self, Vector p))g_hammer_nativeFunctions[519])(m_pSelf, p);
	}
	inline int hasFocus() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[520])(m_pSelf);
	}
	inline int64 focusPolicy() 
	{
		return
		((int64(*)(void* self))g_hammer_nativeFunctions[521])(m_pSelf);
	}
	inline void setFocusPolicy(int64 policy) 
	{
		((void(*)(void* self, int64 policy))g_hammer_nativeFunctions[522])(m_pSelf, policy);
	}
	inline void setFocusProxy(QWidget* widget) 
	{
		((void(*)(void* self, QWidget* widget))g_hammer_nativeFunctions[523])(m_pSelf, widget);
	}
	inline int isActiveWindow() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[524])(m_pSelf);
	}
	inline int updatesEnabled() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[525])(m_pSelf);
	}
	inline void setUpdatesEnabled(int enable) 
	{
		((void(*)(void* self, int enable))g_hammer_nativeFunctions[526])(m_pSelf, enable);
	}
	inline void setFocus() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[527])(m_pSelf);
	}
	inline void activateWindow() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[528])(m_pSelf);
	}
	inline void clearFocus() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[529])(m_pSelf);
	}
	inline float devicePixelRatioF() 
	{
		return
		((float(*)(void* self))g_hammer_nativeFunctions[530])(m_pSelf);
	}
	inline const char* saveGeometry() 
	{
		return
		((const char*(*)(void* self))g_hammer_nativeFunctions[531])(m_pSelf);
	}
	inline int restoreGeometry(const char* state) 
	{
		return
		((int(*)(void* self, const char* state))g_hammer_nativeFunctions[532])(m_pSelf, state);
	}
	inline void addAction(QAction* action) 
	{
		((void(*)(void* self, QAction* action))g_hammer_nativeFunctions[533])(m_pSelf, action);
	}
	inline void removeAction(QAction* action) 
	{
		((void(*)(void* self, QAction* action))g_hammer_nativeFunctions[534])(m_pSelf, action);
	}
	inline void setParent(QWidget* parent) 
	{
		((void(*)(void* self, QWidget* parent))g_hammer_nativeFunctions[535])(m_pSelf, parent);
	}
	inline const QWidget* parentWidget() 
	{
		return
		((const QWidget*(*)(void* self))g_hammer_nativeFunctions[536])(m_pSelf);
	}
	inline const QWidget* window() 
	{
		return
		((const QWidget*(*)(void* self))g_hammer_nativeFunctions[537])(m_pSelf);
	}
	inline void AddClassName(const QChar * name) 
	{
		((void(*)(void* self, const QChar * name))g_hammer_nativeFunctions[538])(m_pSelf, name);
	}
	inline void Polish() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[539])(m_pSelf);
	}
	inline const QChar * toolTip() 
	{
		return
		((const QChar *(*)(void* self))g_hammer_nativeFunctions[540])(m_pSelf);
	}
	inline void setToolTip(const QChar * str) 
	{
		((void(*)(void* self, const QChar * str))g_hammer_nativeFunctions[541])(m_pSelf, str);
	}
	inline const QChar * statusTip() 
	{
		return
		((const QChar *(*)(void* self))g_hammer_nativeFunctions[542])(m_pSelf);
	}
	inline void setStatusTip(const QChar * str) 
	{
		((void(*)(void* self, const QChar * str))g_hammer_nativeFunctions[543])(m_pSelf, str);
	}
	inline int toolTipDuration() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[544])(m_pSelf);
	}
	inline void setToolTipDuration(int x) 
	{
		((void(*)(void* self, int x))g_hammer_nativeFunctions[545])(m_pSelf, x);
	}
	inline int autoFillBackground() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[546])(m_pSelf);
	}
	inline void setAutoFillBackground(int enabled) 
	{
		((void(*)(void* self, int enabled))g_hammer_nativeFunctions[547])(m_pSelf, enabled);
	}
	inline void adjustSize() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[548])(m_pSelf);
	}
	inline int64 windowModality() 
	{
		return
		((int64(*)(void* self))g_hammer_nativeFunctions[549])(m_pSelf);
	}
	inline void setWindowModality(int64 windowModality) 
	{
		((void(*)(void* self, int64 windowModality))g_hammer_nativeFunctions[550])(m_pSelf, windowModality);
	}
	inline QRectF ScreenGeometry() 
	{
		return
		((QRectF(*)(void* __self))g_hammer_nativeFunctions[551])(m_pSelf);
	}
	inline void setContentsMargins(int left, int top, int right, int bottom) 
	{
		((void(*)(void* self, int left, int top, int right, int bottom))g_hammer_nativeFunctions[552])(m_pSelf, left, top, right, bottom);
	}
	inline QRectF contentsMargins() 
	{
		return
		((QRectF(*)(void* __self))g_hammer_nativeFunctions[553])(m_pSelf);
	}
	inline const QLayout* layout() 
	{
		return
		((const QLayout*(*)(void* self))g_hammer_nativeFunctions[554])(m_pSelf);
	}
	inline void setLayout(QLayout* l) 
	{
		((void(*)(void* self, QLayout* l))g_hammer_nativeFunctions[555])(m_pSelf, l);
	}
	inline QRectF contentsRect() 
	{
		return
		((QRectF(*)(void* self))g_hammer_nativeFunctions[556])(m_pSelf);
	}
	inline void SetEffectOpacity(float opacity) 
	{
		((void(*)(void* __self, float __opacity))g_hammer_nativeFunctions[557])(m_pSelf, opacity);
	}
	inline void setSizePolicy(int64 x, int64 y) 
	{
		((void(*)(void* self, int64 x, int64 y))g_hammer_nativeFunctions[558])(m_pSelf, x, y);
	}
	inline int64 GetHorizontalSizePolicy() 
	{
		return
		((int64(*)(void* __self))g_hammer_nativeFunctions[559])(m_pSelf);
	}
	inline int64 GetVerticalSizePolicy() 
	{
		return
		((int64(*)(void* __self))g_hammer_nativeFunctions[560])(m_pSelf);
	}
	inline void SetHorizontalSizePolicy(int64 mode) 
	{
		((void(*)(void* __self, int64 __mode))g_hammer_nativeFunctions[561])(m_pSelf, mode);
	}
	inline void SetVerticalSizePolicy(int64 mode) 
	{
		((void(*)(void* __self, int64 __mode))g_hammer_nativeFunctions[562])(m_pSelf, mode);
	}
	inline void setFixedSize(int w, int h) 
	{
		((void(*)(void* self, int w, int h))g_hammer_nativeFunctions[563])(m_pSelf, w, h);
	}
	inline void setFixedWidth(int w) 
	{
		((void(*)(void* self, int w))g_hammer_nativeFunctions[564])(m_pSelf, w);
	}
	inline void setFixedHeight(int h) 
	{
		((void(*)(void* self, int h))g_hammer_nativeFunctions[565])(m_pSelf, h);
	}
	inline const void* winId() 
	{
		return
		((const void*(*)(void* __self))g_hammer_nativeFunctions[566])(m_pSelf);
	}
	inline void deleteLater() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[567])(m_pSelf);
	}
	inline const QChar * objectName() 
	{
		return
		((const QChar *(*)(void* self))g_hammer_nativeFunctions[568])(m_pSelf);
	}
	inline void setObjectName(const QChar * name) 
	{
		((void(*)(void* self, const QChar * name))g_hammer_nativeFunctions[569])(m_pSelf, name);
	}
	inline void setParent(QObject* parent) 
	{
		((void(*)(void* __self, QObject* __parent))g_hammer_nativeFunctions[570])(m_pSelf, parent);
	}
	inline void setProperty(const char* key, int value) 
	{
		((void(*)(void* self, const char* key, int value))g_hammer_nativeFunctions[571])(m_pSelf, key, value);
	}
	inline void setProperty(const char* key, float value) 
	{
		((void(*)(void* self, const char* key, float value))g_hammer_nativeFunctions[572])(m_pSelf, key, value);
	}
	inline void setProperty(const char* key, const char* value) 
	{
		((void(*)(void* self, const char* key, const char* value))g_hammer_nativeFunctions[573])(m_pSelf, key, value);
	}
};
class CSavedObjects
{
	public:
	void *m_pSelf;
	inline operator CSavedObjects*()
	{
		return (CSavedObjects*)m_pSelf;
	}
	inline void DeleteThis() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[574])(m_pSelf);
	}
	CSavedObjects() 
	{
		m_pSelf = ((void*(*)())g_hammer_nativeFunctions[575])();
	}
	inline void RemoveAll() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[576])(m_pSelf);
	}
	inline void SaveObject(CMapNode* pObject) 
	{
		((void(*)(void* self, CMapNode* pObject))g_hammer_nativeFunctions[577])(m_pSelf, pObject);
	}
	inline void RestoreObjects() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[578])(m_pSelf);
	}
	inline int Count() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[579])(m_pSelf);
	}
};
class CSelection
{
	public:
	void *m_pSelf;
	inline operator CSelection*()
	{
		return (CSelection*)m_pSelf;
	}
	inline int64 GetMode() 
	{
		return
		((int64(*)(void* self))g_hammer_nativeFunctions[580])(m_pSelf);
	}
	inline void SetMode(int64 mode, int64 method) 
	{
		((void(*)(void* self, int64 mode, int64 method))g_hammer_nativeFunctions[581])(m_pSelf, mode, method);
	}
	inline const ISelectionSet* ActiveSelectionSet() 
	{
		return
		((const ISelectionSet*(*)(void* __self))g_hammer_nativeFunctions[582])(m_pSelf);
	}
	inline const ISelectionSet* GetSelectionSetForMode(int64 nMode) 
	{
		return
		((const ISelectionSet*(*)(void* self, int64 nMode))g_hammer_nativeFunctions[583])(m_pSelf, nMode);
	}
	inline int GetNumSelectionSets() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[584])(m_pSelf);
	}
	inline const ISelectionSet* GetSelectionSet(int nIndex) 
	{
		return
		((const ISelectionSet*(*)(void* self, int nIndex))g_hammer_nativeFunctions[585])(m_pSelf, nIndex);
	}
};
class CToolBlock
{
	public:
	void *m_pSelf;
	inline operator CToolBlock*()
	{
		return (CToolBlock*)m_pSelf;
	}
	inline void OnObjectTypeChanged() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[586])(m_pSelf);
	}
	inline void SetPrimitiveType2D(int primitiveIs2D) 
	{
		((void(*)(void* self, int primitiveIs2D))g_hammer_nativeFunctions[587])(m_pSelf, primitiveIs2D);
	}
	inline int GetOrientPrimitives() 
	{
		return
		((int(*)(void* __self))g_hammer_nativeFunctions[588])(m_pSelf);
	}
	inline void SetOrientPrimitives(int bOrientPrimitives) 
	{
		((void(*)(void* __self, int __bOrientPrimitives))g_hammer_nativeFunctions[589])(m_pSelf, bOrientPrimitives);
	}
	RW_VAR(const char*,m_OverrideMaterial,CToolBlock,g_hammer_nativeFunctions[590],g_hammer_nativeFunctions[591]);
};
class CToolBlockState
{
	public:
	void *m_pSelf;
	inline operator CToolBlockState*()
	{
		return (CToolBlockState*)m_pSelf;
	}
	inline AABB_t GetAABBBounds() 
	{
		return
		((AABB_t(*)(void* __self))g_hammer_nativeFunctions[592])(m_pSelf);
	}
	inline const CWorkPlane* GetDragWorkPlane() 
	{
		return
		((const CWorkPlane*(*)(void* self))g_hammer_nativeFunctions[593])(m_pSelf);
	}
};
class CToolCamera
{
	public:
	void *m_pSelf;
	inline operator CToolCamera*()
	{
		return (CToolCamera*)m_pSelf;
	}
	inline Vector GetOrigin() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[594])(m_pSelf);
	}
	inline QAngle GetAngles() 
	{
		return
		((QAngle(*)(void* self))g_hammer_nativeFunctions[595])(m_pSelf);
	}
	inline void SetOrigin(Vector origin) 
	{
		((void(*)(void* self, Vector origin))g_hammer_nativeFunctions[596])(m_pSelf, origin);
	}
	inline void SetAngles(QAngle angles) 
	{
		((void(*)(void* self, QAngle angles))g_hammer_nativeFunctions[597])(m_pSelf, angles);
	}
	inline float GetWidth() 
	{
		return
		((float(*)(void* self))g_hammer_nativeFunctions[598])(m_pSelf);
	}
	inline float GetHeight() 
	{
		return
		((float(*)(void* self))g_hammer_nativeFunctions[599])(m_pSelf);
	}
	inline float GetCameraFOV() 
	{
		return
		((float(*)(void* self))g_hammer_nativeFunctions[600])(m_pSelf);
	}
	inline void BuildRay(Vector2D view, Vector* start, Vector* end) 
	{
		((void(*)(void* __self, Vector2D __view, Vector* __start, Vector* __end))g_hammer_nativeFunctions[601])(m_pSelf, view, start, end);
	}
};
class CToolEntity
{
	public:
	void *m_pSelf;
	inline operator CToolEntity*()
	{
		return (CToolEntity*)m_pSelf;
	}
	inline void StartBlockEntityCreation(const char* className) 
	{
		((void(*)(void* self, const char* className))g_hammer_nativeFunctions[602])(m_pSelf, className);
	}
};
class CWorkPlane
{
	public:
	void *m_pSelf;
	inline operator CWorkPlane*()
	{
		return (CWorkPlane*)m_pSelf;
	}
	inline VMatrix GetWorkPlaneToWorldTransform() 
	{
		return
		((VMatrix(*)(void* self))g_hammer_nativeFunctions[603])(m_pSelf);
	}
};
static
inline int MaterialGetMappingWidth(HMaterialStrong* material) 
{
	return
	((int(*)(HMaterialStrong* material))g_hammer_nativeFunctions[604])(material);
}
static
inline int MaterialGetMappingHeight(HMaterialStrong* material) 
{
	return
	((int(*)(HMaterialStrong* material))g_hammer_nativeFunctions[605])(material);
}
class ISelectionSet
{
	public:
	void *m_pSelf;
	inline operator ISelectionSet*()
	{
		return (ISelectionSet*)m_pSelf;
	}
	inline int SelectObject(CMapNode* pObject, int64 selectOp) 
	{
		return
		((int(*)(void* self, CMapNode* pObject, int64 selectOp))g_hammer_nativeFunctions[606])(m_pSelf, pObject, selectOp);
	}
	inline int GetSelectedObject(int nIndex) 
	{
		return
		((int(*)(void* __self, int __nIndex))g_hammer_nativeFunctions[607])(m_pSelf, nIndex);
	}
	inline int Count() 
	{
		return
		((int(*)(void* self))g_hammer_nativeFunctions[608])(m_pSelf);
	}
	inline void RemoveAll() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[609])(m_pSelf);
	}
	inline void SelectAll() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[610])(m_pSelf);
	}
	inline void InvertSelection() 
	{
		((void(*)(void* self))g_hammer_nativeFunctions[611])(m_pSelf);
	}
	inline Vector GetPivotPosition() 
	{
		return
		((Vector(*)(void* self))g_hammer_nativeFunctions[612])(m_pSelf);
	}
	inline void SetPivot(Vector pivot) 
	{
		((void(*)(void* self, Vector pivot))g_hammer_nativeFunctions[613])(m_pSelf, pivot);
	}
};
class NativeHammer::Options
{
	public:
	void *m_pSelf;
	inline operator NativeHammer::Options*()
	{
		return (NativeHammer::Options*)m_pSelf;
	}
	static
	inline int GetShowHelpers() 
	{
		return
		((int(*)())g_hammer_nativeFunctions[614])();
	}
	static
	inline int GetShowGameObjectsOnly() 
	{
		return
		((int(*)())g_hammer_nativeFunctions[615])();
	}
};
#undef ConVar
#undef ConCommand
#undef CUtlBuffer
#undef CUtlString
#undef CUtlVector
inline void hammerFree()
{
	if ( g_phammerLibrary == 0 ) return;
	FreeLibrary( (HMODULE)g_phammerLibrary );
	g_phammerLibrary = 0;
	g_bIshammerInitialized = false;
}
#endif
