// <auto-generated>
// This file was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#ifndef animgraph_GEN_H
#define animgraph_GEN_H
extern void *g_panimgraphLibrary;
extern bool g_bIsanimgraphInitialized;

#include "windows.h" 
#include "engine/structs.h" 
#ifdef _WIN32
#define CC __stdcall
#else
#define CC
#endif

#define RW_VAR(type, name, parent, readop, writeop) RWVariable<type, parent> name{readop, writeop,this};
#define ConVar _ConVar
#define ConCommand _ConCommand
#define CUtlBuffer _CUtlBuffer
#define CUtlString _CUtlString
#define CUtlVector _CUtlVector


extern void *g_animgraph_nativeFunctions[3];
extern void *g_animgraph_callbackFunctions[1];
extern int g_animgraph_iStructSizes[129];
typedef int(*FnBindingsImportDelegate)( int hash, void* imports, void* exports, int* structSizes );

inline void animgraphBindingsInitialize()
{
	if ( g_bIsanimgraphInitialized ) return;
	
	g_panimgraphLibrary = LoadLibraryA("tools/animgraph_editor.dll");
	if(!g_panimgraphLibrary)
		_exit(1);
	
	FnBindingsImportDelegate igen_animgraph = (FnBindingsImportDelegate)GetProcAddress( (HMODULE)g_panimgraphLibrary, "igen_animgraph" );
	if(!igen_animgraph)
		_exit(1);
	
	void *managedFunctions[1] = 
	
	{
		(void*) (g_animgraph_callbackFunctions[0]),
	};
	
	igen_animgraph( *(unsigned short*)(((uint64_t)igen_animgraph)+23), managedFunctions, g_animgraph_nativeFunctions, g_animgraph_iStructSizes );
	g_bIsanimgraphInitialized = true;
}
class CQAnimGraphPreviewDockWidget
{
	public:
	void *m_pSelf;
	inline operator CQAnimGraphPreviewDockWidget*()
	{
		return (CQAnimGraphPreviewDockWidget*)m_pSelf;
	}
	inline const char* GetPreviewModel() 
	{
		return
		((const char*(*)(void* self))g_animgraph_nativeFunctions[1])(m_pSelf);
	}
	inline void SetPreviewModel(const char* model) 
	{
		((void(*)(void* self, const char* model))g_animgraph_nativeFunctions[2])(m_pSelf, model);
	}
};
#undef ConVar
#undef ConCommand
#undef CUtlBuffer
#undef CUtlString
#undef CUtlVector
inline void animgraphFree()
{
	if ( g_panimgraphLibrary == 0 ) return;
	FreeLibrary( (HMODULE)g_panimgraphLibrary );
	g_panimgraphLibrary = 0;
	g_bIsanimgraphInitialized = false;
}
#endif
