// <auto-generated>
// This file was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#ifndef modeldoc_GEN_H
#define modeldoc_GEN_H
extern void *g_pmodeldocLibrary;
extern bool g_bIsmodeldocInitialized;

#include "windows.h" 
#include "engine/structs.h" 
#ifdef _WIN32
#define CC __stdcall
#else
#define CC
#endif

#define RW_VAR(type, name, parent, readop, writeop) RWVariable<type, parent> name{readop, writeop,this};
#define ConVar _ConVar
#define ConCommand _ConCommand
#define CUtlBuffer _CUtlBuffer
#define CUtlString _CUtlString
#define CUtlVector _CUtlVector


extern void *g_modeldoc_nativeFunctions[18];
extern void *g_modeldoc_callbackFunctions[2];
extern int g_modeldoc_iStructSizes[129];
typedef int(*FnBindingsImportDelegate)( int hash, void* imports, void* exports, int* structSizes );

inline void modeldocBindingsInitialize()
{
	if ( g_bIsmodeldocInitialized ) return;
	
	g_pmodeldocLibrary = LoadLibraryA("tools/modeldoc_editor.dll");
	if(!g_pmodeldocLibrary)
		_exit(1);
	
	FnBindingsImportDelegate igen_modeldoc = (FnBindingsImportDelegate)GetProcAddress( (HMODULE)g_pmodeldocLibrary, "igen_modeldoc" );
	if(!igen_modeldoc)
		_exit(1);
	
	void *managedFunctions[2] = 
	
	{
		(void*) (g_modeldoc_callbackFunctions[0]),
		(void*) (g_modeldoc_callbackFunctions[1]),
	};
	
	igen_modeldoc( *(unsigned short*)(((uint64_t)igen_modeldoc)+23), managedFunctions, g_modeldoc_nativeFunctions, g_modeldoc_iStructSizes );
	g_bIsmodeldocInitialized = true;
}
class CModelDoc
{
	public:
	void *m_pSelf;
	inline operator CModelDoc*()
	{
		return (CModelDoc*)m_pSelf;
	}
	inline void DeleteThis() 
	{
		((void(*)(void* self))g_modeldoc_nativeFunctions[1])(m_pSelf);
	}
	CModelDoc() 
	{
		m_pSelf = ((void*(*)())g_modeldoc_nativeFunctions[2])();
	}
	inline int SaveToFile(const char* pFullPath) 
	{
		return
		((int(*)(void* __self, const char* __pFullPath))g_modeldoc_nativeFunctions[3])(m_pSelf, pFullPath);
	}
};
class CModelDocEditorApp
{
	public:
	void *m_pSelf;
	inline operator CModelDocEditorApp*()
	{
		return (CModelDocEditorApp*)m_pSelf;
	}
	inline void RefreshGameData() 
	{
		((void(*)(void* self))g_modeldoc_nativeFunctions[4])(m_pSelf);
	}
	inline const char* GetSessionModel() 
	{
		return
		((const char*(*)(void* __self))g_modeldoc_nativeFunctions[5])(m_pSelf);
	}
};
class CModelMesh
{
	public:
	void *m_pSelf;
	inline operator CModelMesh*()
	{
		return (CModelMesh*)m_pSelf;
	}
	inline void DeleteThis() 
	{
		((void(*)(void* self))g_modeldoc_nativeFunctions[6])(m_pSelf);
	}
	CModelMesh() 
	{
		m_pSelf = ((void*(*)())g_modeldoc_nativeFunctions[7])();
	}
	inline void AddVertices(int nNumVertices) 
	{
		((void(*)(void* self, int nNumVertices))g_modeldoc_nativeFunctions[8])(m_pSelf, nNumVertices);
	}
	inline void AddFaceGroup(const char* pMaterialName) 
	{
		((void(*)(void* __self, const char* __pMaterialName))g_modeldoc_nativeFunctions[9])(m_pSelf, pMaterialName);
	}
	inline void SetPositions(void* pPositions, int nNumPositions) 
	{
		((void(*)(void* __self, void* __pPositions, int __nNumPositions))g_modeldoc_nativeFunctions[10])(m_pSelf, pPositions, nNumPositions);
	}
	inline void SetTexCoords(void* pTexCoords, int nNumTexCoords) 
	{
		((void(*)(void* __self, void* __pTexCoords, int __nNumTexCoords))g_modeldoc_nativeFunctions[11])(m_pSelf, pTexCoords, nNumTexCoords);
	}
	inline void SetNormals(void* pNormals, int nNumNormals) 
	{
		((void(*)(void* __self, void* __pNormals, int __nNumNormals))g_modeldoc_nativeFunctions[12])(m_pSelf, pNormals, nNumNormals);
	}
	inline void AddFace(int nGroupIndex, void* pVertices, int nNumVertices) 
	{
		((void(*)(void* __self, int __nGroupIndex, void* __pVertices, int __nNumVertices))g_modeldoc_nativeFunctions[13])(m_pSelf, nGroupIndex, pVertices, nNumVertices);
	}
};
class g_pModelDocUtils
{
	public:
	void *m_pSelf;
	inline operator g_pModelDocUtils*()
	{
		return (g_pModelDocUtils*)m_pSelf;
	}
	inline int InitFromMesh(CModelDoc* pModelDoc, const char* pFilename) 
	{
		return
		((int(*)(CModelDoc* pModelDoc, const char* pFilename))g_modeldoc_nativeFunctions[14])(pModelDoc, pFilename);
	}
};
class NativeEngine::ModelDoc
{
	public:
	void *m_pSelf;
	inline operator NativeEngine::ModelDoc*()
	{
		return (NativeEngine::ModelDoc*)m_pSelf;
	}
	static
	inline int CreateModelFromMeshFile(const char* pVmdlFileFullPath, const char* meshRelativePath, const char* material) 
	{
		return
		((int(*)(const char* __pVmdlFileFullPath, const char* __meshRelativePath, const char* __material))g_modeldoc_nativeFunctions[15])(pVmdlFileFullPath, meshRelativePath, material);
	}
	static
	inline int CreateModelFromMesh(const char* pVmdlFileFullPath, CModelMesh* pMesh) 
	{
		return
		((int(*)(const char* __pVmdlFileFullPath, CModelMesh* __pMesh))g_modeldoc_nativeFunctions[16])(pVmdlFileFullPath, pMesh);
	}
	static
	inline int CreateModelFromMeshes(const char* pVmdlFileFullPath, void* pMeshes, int nMeshCount) 
	{
		return
		((int(*)(const char* __pVmdlFileFullPath, void* __pMeshes, int __nMeshCount))g_modeldoc_nativeFunctions[17])(pVmdlFileFullPath, pMeshes, nMeshCount);
	}
};
#undef ConVar
#undef ConCommand
#undef CUtlBuffer
#undef CUtlString
#undef CUtlVector
inline void modeldocFree()
{
	if ( g_pmodeldocLibrary == 0 ) return;
	FreeLibrary( (HMODULE)g_pmodeldocLibrary );
	g_pmodeldocLibrary = 0;
	g_bIsmodeldocInitialized = false;
}
#endif
