// <auto-generated>
// This file was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#ifndef assetsystem_GEN_H
#define assetsystem_GEN_H
extern void *g_passetsystemLibrary;
extern bool g_bIsassetsystemInitialized;

#include "windows.h" 
#include "engine/structs.h" 
#ifdef _WIN32
#define CC __stdcall
#else
#define CC
#endif

#define RW_VAR(type, name, parent, readop, writeop) RWVariable<type, parent> name{readop, writeop,this};
#define ConVar _ConVar
#define ConCommand _ConCommand
#define CUtlBuffer _CUtlBuffer
#define CUtlString _CUtlString
#define CUtlVector _CUtlVector


extern void *g_assetsystem_nativeFunctions[100];
extern void *g_assetsystem_callbackFunctions[15];
extern int g_assetsystem_iStructSizes[131];
typedef int(*FnBindingsImportDelegate)( int hash, void* imports, void* exports, int* structSizes );

inline void assetsystemBindingsInitialize()
{
	if ( g_bIsassetsystemInitialized ) return;
	
	g_passetsystemLibrary = LoadLibraryA("assetsystem.dll");
	if(!g_passetsystemLibrary)
		_exit(1);
	
	FnBindingsImportDelegate igen_assetsystem = (FnBindingsImportDelegate)GetProcAddress( (HMODULE)g_passetsystemLibrary, "igen_assetsystem" );
	if(!igen_assetsystem)
		_exit(1);
	
	void *managedFunctions[15] = 
	
	{
		(void*) (g_assetsystem_callbackFunctions[0]),
		(void*) (g_assetsystem_callbackFunctions[1]),
		(void*) (g_assetsystem_callbackFunctions[2]),
		(void*) (g_assetsystem_callbackFunctions[3]),
		(void*) (g_assetsystem_callbackFunctions[4]),
		(void*) (g_assetsystem_callbackFunctions[5]),
		(void*) (g_assetsystem_callbackFunctions[6]),
		(void*) (g_assetsystem_callbackFunctions[7]),
		(void*) (g_assetsystem_callbackFunctions[8]),
		(void*) (g_assetsystem_callbackFunctions[9]),
		(void*) (g_assetsystem_callbackFunctions[10]),
		(void*) (g_assetsystem_callbackFunctions[11]),
		(void*) (g_assetsystem_callbackFunctions[12]),
		(void*) (g_assetsystem_callbackFunctions[13]),
		(void*) (g_assetsystem_callbackFunctions[14]),
	};
	
	igen_assetsystem( *(unsigned short*)(((uint64_t)igen_assetsystem)+23), managedFunctions, g_assetsystem_nativeFunctions, g_assetsystem_iStructSizes );
	g_bIsassetsystemInitialized = true;
}
class AssetPickedWrapper
{
	public:
	void *m_pSelf;
	inline operator AssetPickedWrapper*()
	{
		return (AssetPickedWrapper*)m_pSelf;
	}
	inline void DeleteThis() 
	{
		((void(*)(void* self))g_assetsystem_nativeFunctions[1])(m_pSelf);
	}
	AssetPickedWrapper() 
	{
		m_pSelf = ((void*(*)())g_assetsystem_nativeFunctions[2])();
	}
	inline void AddAsset(IAsset* asset) 
	{
		((void(*)(void* self, IAsset* asset))g_assetsystem_nativeFunctions[3])(m_pSelf, asset);
	}
};
class CResourceStream
{
	public:
	void *m_pSelf;
	inline operator CResourceStream*()
	{
		return (CResourceStream*)m_pSelf;
	}
	inline void WriteBytes(void* data, int size) 
	{
		((void(*)(void* self, void* data, int size))g_assetsystem_nativeFunctions[4])(m_pSelf, data, size);
	}
	inline void Align(int alignment, int offset) 
	{
		((void(*)(void* self, int alignment, int offset))g_assetsystem_nativeFunctions[5])(m_pSelf, alignment, offset);
	}
	inline void AlignPointer() 
	{
		((void(*)(void* self))g_assetsystem_nativeFunctions[6])(m_pSelf);
	}
	inline unsigned int Tell() 
	{
		return
		((unsigned int(*)(void* self))g_assetsystem_nativeFunctions[7])(m_pSelf);
	}
};
class CUtlVector<IAsset*>
{
	public:
	void *m_pSelf;
	inline operator CUtlVector<IAsset*>*()
	{
		return (CUtlVector<IAsset*>*)m_pSelf;
	}
	inline void DeleteThis() 
	{
		((void(*)(void* self))g_assetsystem_nativeFunctions[8])(m_pSelf);
	}
	CUtlVector<IAsset*>(int growsize, int initialcapacity) 
	{
		m_pSelf = ((void*(*)(int growsize, int initialcapacity))g_assetsystem_nativeFunctions[9])(growsize, initialcapacity);
	}
	inline int Count() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[10])(m_pSelf);
	}
	inline const IAsset* Element(int i) 
	{
		return
		((const IAsset*(*)(void* self, int i))g_assetsystem_nativeFunctions[11])(m_pSelf, i);
	}
};
class CUtlVector<IAssetType*>
{
	public:
	void *m_pSelf;
	inline operator CUtlVector<IAssetType*>*()
	{
		return (CUtlVector<IAssetType*>*)m_pSelf;
	}
	inline void DeleteThis() 
	{
		((void(*)(void* self))g_assetsystem_nativeFunctions[12])(m_pSelf);
	}
	CUtlVector<IAssetType*>(int growsize, int initialcapacity) 
	{
		m_pSelf = ((void*(*)(int growsize, int initialcapacity))g_assetsystem_nativeFunctions[13])(growsize, initialcapacity);
	}
	inline int Count() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[14])(m_pSelf);
	}
	inline const IAssetType* Element(int i) 
	{
		return
		((const IAssetType*(*)(void* self, int i))g_assetsystem_nativeFunctions[15])(m_pSelf, i);
	}
};
class g_pAssetPreviewSystem
{
	public:
	void *m_pSelf;
	inline operator g_pAssetPreviewSystem*()
	{
		return (g_pAssetPreviewSystem*)m_pSelf;
	}
	inline int RenderAssetThumbnail(IAsset* pAsset, QPixmap* targetPixmap) 
	{
		return
		((int(*)(IAsset* pAsset, QPixmap* targetPixmap))g_assetsystem_nativeFunctions[16])(pAsset, targetPixmap);
	}
	inline void OnThumbnailGenerated(IAsset* asset, QPixmap* renderedPixmap) 
	{
		((void(*)(IAsset* asset, QPixmap* renderedPixmap))g_assetsystem_nativeFunctions[17])(asset, renderedPixmap);
	}
	inline HModelStrong* GetModelForAsset(IAsset* pAsset) 
	{
		return
		((HModelStrong*(*)(IAsset* pAsset))g_assetsystem_nativeFunctions[18])(pAsset);
	}
};
class g_pAssetSystem
{
	public:
	void *m_pSelf;
	inline operator g_pAssetSystem*()
	{
		return (g_pAssetSystem*)m_pSelf;
	}
	inline void RecordAssetOpen(IAsset* pAsset) 
	{
		((void(*)(IAsset* pAsset))g_assetsystem_nativeFunctions[19])(pAsset);
	}
	inline void RecordAssetOpen(const char* pAssetFileName) 
	{
		((void(*)(const char* pAssetFileName))g_assetsystem_nativeFunctions[20])(pAssetFileName);
	}
	inline const IAsset* FindAssetByFilename(const char* pFilename) 
	{
		return
		((const IAsset*(*)(const char* pFilename))g_assetsystem_nativeFunctions[21])(pFilename);
	}
	inline const IAsset* FindAssetByAssetRelativePath(const char* pFilename) 
	{
		return
		((const IAsset*(*)(const char* pFilename))g_assetsystem_nativeFunctions[22])(pFilename);
	}
	inline const IAsset* RegisterAssetFile(const char* pFilename) 
	{
		return
		((const IAsset*(*)(const char* pFilename))g_assetsystem_nativeFunctions[23])(pFilename);
	}
	inline void RunFrame() 
	{
		((void(*)())g_assetsystem_nativeFunctions[24])();
	}
	inline void UpdateMods() 
	{
		((void(*)())g_assetsystem_nativeFunctions[25])();
	}
	inline int GetAllModsCount() 
	{
		return
		((int(*)())g_assetsystem_nativeFunctions[26])();
	}
	inline int RecompileAsset(IAsset* asset, int full) 
	{
		return
		((int(*)(IAsset* __asset, int __full))g_assetsystem_nativeFunctions[27])(asset, full);
	}
	inline void UpdateGameResourceType(const char* title, const char* extension) 
	{
		((void(*)(const char* title, const char* extension))g_assetsystem_nativeFunctions[28])(title, extension);
	}
	inline void LoadWorkingSetsAndTags() 
	{
		((void(*)())g_assetsystem_nativeFunctions[29])();
	}
};
class IAsset
{
	public:
	void *m_pSelf;
	inline operator IAsset*()
	{
		return (IAsset*)m_pSelf;
	}
	inline const char* GetFriendlyName_Transient() 
	{
		return
		((const char*(*)(void* self))g_assetsystem_nativeFunctions[30])(m_pSelf);
	}
	inline const char* GetRelativePath_Transient(int64 source) 
	{
		return
		((const char*(*)(void* self, int64 source))g_assetsystem_nativeFunctions[31])(m_pSelf, source);
	}
	inline const char* GetAbsolutePath_Transient(int64 source) 
	{
		return
		((const char*(*)(void* self, int64 source))g_assetsystem_nativeFunctions[32])(m_pSelf, source);
	}
	inline int HasAnyFiles() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[33])(m_pSelf);
	}
	inline int IsCached() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[34])(m_pSelf);
	}
	inline int CanReload() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[35])(m_pSelf);
	}
	inline int CanRecompile() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[36])(m_pSelf);
	}
	inline unsigned int GetAssetIndexInt() 
	{
		return
		((unsigned int(*)(void* self))g_assetsystem_nativeFunctions[37])(m_pSelf);
	}
	inline int OpenInTool() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[38])(m_pSelf);
	}
	inline int OpenInSecondaryTool(const char* tool) 
	{
		return
		((int(*)(void* __self, const char* __tool))g_assetsystem_nativeFunctions[39])(m_pSelf, tool);
	}
	inline void GetAssetsIDependOn(CUtlVector<IAsset*>* pOutAssetsIDependOn, int bDeep) 
	{
		((void(*)(void* self, CUtlVector<IAsset*>* pOutAssetsIDependOn, int bDeep))g_assetsystem_nativeFunctions[40])(m_pSelf, pOutAssetsIDependOn, bDeep);
	}
	inline void GetAssetsIParent(CUtlVector<IAsset*>* pOutChildren, int bDeep) 
	{
		((void(*)(void* self, CUtlVector<IAsset*>* pOutChildren, int bDeep))g_assetsystem_nativeFunctions[41])(m_pSelf, pOutChildren, bDeep);
	}
	inline void GetAssetsIReference(CUtlVector<IAsset*>* pOutReferencers, int bDeep) 
	{
		((void(*)(void* self, CUtlVector<IAsset*>* pOutReferencers, int bDeep))g_assetsystem_nativeFunctions[42])(m_pSelf, pOutReferencers, bDeep);
	}
	inline void GetAssetsDependingOnMe(CUtlVector<IAsset*>* pOutDependencies, int bDeep) 
	{
		((void(*)(void* self, CUtlVector<IAsset*>* pOutDependencies, int bDeep))g_assetsystem_nativeFunctions[43])(m_pSelf, pOutDependencies, bDeep);
	}
	inline void GetAssetsReferencingMe(CUtlVector<IAsset*>* pOutReferencers, int bDeep) 
	{
		((void(*)(void* self, CUtlVector<IAsset*>* pOutReferencers, int bDeep))g_assetsystem_nativeFunctions[44])(m_pSelf, pOutReferencers, bDeep);
	}
	inline void GetAssetsParentingMe(CUtlVector<IAsset*>* pOutParents, int bDeep) 
	{
		((void(*)(void* self, CUtlVector<IAsset*>* pOutParents, int bDeep))g_assetsystem_nativeFunctions[45])(m_pSelf, pOutParents, bDeep);
	}
	inline int AdditionalRelatedFileCount() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[46])(m_pSelf);
	}
	inline int AdditionalInputDependencyCount() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[47])(m_pSelf);
	}
	inline const char* GetAdditionalRelatedFile_Transient(int nIndex) 
	{
		return
		((const char*(*)(void* self, int nIndex))g_assetsystem_nativeFunctions[48])(m_pSelf, nIndex);
	}
	inline const char* GetAdditionalInputDependency_Transient(int nIndex) 
	{
		return
		((const char*(*)(void* self, int nIndex))g_assetsystem_nativeFunctions[49])(m_pSelf, nIndex);
	}
	inline void GetUnrecognizedRelatedPaths(int64 filterType, CUtlVector<CUtlString>* paths) 
	{
		((void(*)(void* __self, int64 __filterType, CUtlVector<CUtlString>* __paths))g_assetsystem_nativeFunctions[50])(m_pSelf, filterType, paths);
	}
	inline void RequireDependencyInfo_Virtual() 
	{
		((void(*)(void* self))g_assetsystem_nativeFunctions[51])(m_pSelf);
	}
	inline int NeedAnyDependencyUpdate_Virtual() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[52])(m_pSelf);
	}
	inline int IsTrivialChildAsset() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[53])(m_pSelf);
	}
	inline int HasHiddenAssetFlag() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[54])(m_pSelf);
	}
	inline int GetAssetTypeId() 
	{
		return
		((int(*)(void* __self))g_assetsystem_nativeFunctions[55])(m_pSelf);
	}
	inline void CacheAsset(int bIsBlocking) 
	{
		((void(*)(void* self, int bIsBlocking))g_assetsystem_nativeFunctions[56])(m_pSelf, bIsBlocking);
	}
	inline void UncacheAsset() 
	{
		((void(*)(void* self))g_assetsystem_nativeFunctions[57])(m_pSelf);
	}
	inline int HasSourceFile() 
	{
		return
		((int(*)(void* __self))g_assetsystem_nativeFunctions[58])(m_pSelf);
	}
	inline int HasCompiledFile() 
	{
		return
		((int(*)(void* __self))g_assetsystem_nativeFunctions[59])(m_pSelf);
	}
	inline int IsCompiled() 
	{
		return
		((int(*)(void* __self))g_assetsystem_nativeFunctions[60])(m_pSelf);
	}
	inline int IsCompiledAndUpToDate() 
	{
		return
		((int(*)(void* __self))g_assetsystem_nativeFunctions[61])(m_pSelf);
	}
	inline int IsCompileFailed() 
	{
		return
		((int(*)(void* __self))g_assetsystem_nativeFunctions[62])(m_pSelf);
	}
	inline int CompileIfNeeded() 
	{
		return
		((int(*)(void* __self))g_assetsystem_nativeFunctions[63])(m_pSelf);
	}
	inline int FindIntEditInfo(const char* name) 
	{
		return
		((int(*)(void* __self, const char* __name))g_assetsystem_nativeFunctions[64])(m_pSelf, name);
	}
	inline const char* FindStringEditInfo(const char* name) 
	{
		return
		((const char*(*)(void* __self, const char* __name))g_assetsystem_nativeFunctions[65])(m_pSelf, name);
	}
	inline const char* GetCompileStateReason_Transient() 
	{
		return
		((const char*(*)(void* self))g_assetsystem_nativeFunctions[66])(m_pSelf);
	}
	inline int SetInMemoryReplacement(const char* data) 
	{
		return
		((int(*)(void* __self, const char* __data))g_assetsystem_nativeFunctions[67])(m_pSelf, data);
	}
	inline void DiscardInMemoryReplacement() 
	{
		((void(*)(void* self))g_assetsystem_nativeFunctions[68])(m_pSelf);
	}
};
class IAssetPickerListener
{
	public:
	void *m_pSelf;
	inline operator IAssetPickerListener*()
	{
		return (IAssetPickerListener*)m_pSelf;
	}
	inline void NotifyAssetPicked(AssetPickedWrapper* wrapper) 
	{
		((void(*)(void* __self, AssetPickedWrapper* __wrapper))g_assetsystem_nativeFunctions[69])(m_pSelf, wrapper);
	}
};
class IAssetType
{
	public:
	void *m_pSelf;
	inline operator IAssetType*()
	{
		return (IAssetType*)m_pSelf;
	}
	inline const char* GetFriendlyName() 
	{
		return
		((const char*(*)(void* self))g_assetsystem_nativeFunctions[70])(m_pSelf);
	}
	inline const char* GetIconLg() 
	{
		return
		((const char*(*)(void* self))g_assetsystem_nativeFunctions[71])(m_pSelf);
	}
	inline const char* GetIconSm() 
	{
		return
		((const char*(*)(void* self))g_assetsystem_nativeFunctions[72])(m_pSelf);
	}
	inline const char* GetPrimaryExtension() 
	{
		return
		((const char*(*)(void* self))g_assetsystem_nativeFunctions[73])(m_pSelf);
	}
	inline const char* GetColor() 
	{
		return
		((const char*(*)(void* self))g_assetsystem_nativeFunctions[74])(m_pSelf);
	}
	inline const char* GetCategory() 
	{
		return
		((const char*(*)(void* self))g_assetsystem_nativeFunctions[75])(m_pSelf);
	}
	inline int HideTypeByDefault() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[76])(m_pSelf);
	}
	inline int IgnoreCompiledState() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[77])(m_pSelf);
	}
	inline int IsContentFileText() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[78])(m_pSelf);
	}
	inline int IsSimpleAsset() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[79])(m_pSelf);
	}
	inline int HasDependencies() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[80])(m_pSelf);
	}
	inline int PrefersIconForThumbnail() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[81])(m_pSelf);
	}
	inline const char* GetAssetTypeName() 
	{
		return
		((const char*(*)(void* self))g_assetsystem_nativeFunctions[82])(m_pSelf);
	}
	inline void GetAdditionalExtensions(CUtlVector<CUtlString>* pExts) 
	{
		((void(*)(void* self, CUtlVector<CUtlString>* pExts))g_assetsystem_nativeFunctions[83])(m_pSelf, pExts);
	}
};
class IResourceCompilerContext
{
	public:
	void *m_pSelf;
	inline operator IResourceCompilerContext*()
	{
		return (IResourceCompilerContext*)m_pSelf;
	}
	inline void SetExtension(const char* name) 
	{
		((void(*)(void* self, const char* name))g_assetsystem_nativeFunctions[84])(m_pSelf, name);
	}
	inline void SetCompiler(const char* name) 
	{
		((void(*)(void* self, const char* name))g_assetsystem_nativeFunctions[85])(m_pSelf, name);
	}
	inline const char* FullPath() 
	{
		return
		((const char*(*)(void* self))g_assetsystem_nativeFunctions[86])(m_pSelf);
	}
	inline const char* RelativePath() 
	{
		return
		((const char*(*)(void* self))g_assetsystem_nativeFunctions[87])(m_pSelf);
	}
	inline const char* ResourceName() 
	{
		return
		((const char*(*)(void* self))g_assetsystem_nativeFunctions[88])(m_pSelf);
	}
	inline void SpecifyResourceVersion(int nVersion) 
	{
		((void(*)(void* self, int nVersion))g_assetsystem_nativeFunctions[89])(m_pSelf, nVersion);
	}
	inline void RegisterSpecialDependency(const char* str, unsigned int nUserData, unsigned int nFingerprint) 
	{
		((void(*)(void* self, const char* str, unsigned int nUserData, unsigned int nFingerprint))g_assetsystem_nativeFunctions[90])(m_pSelf, str, nUserData, nFingerprint);
	}
	inline int RegisterReference(const char* filename) 
	{
		return
		((int(*)(void* __self, const char* __filename))g_assetsystem_nativeFunctions[91])(m_pSelf, filename);
	}
	inline void RegisterInputFileDependency(const char* filename, int flags) 
	{
		((void(*)(void* __self, const char* __filename, int __flags))g_assetsystem_nativeFunctions[92])(m_pSelf, filename, flags);
	}
	inline int WriteBlock(const char* blockName, void* data, int count) 
	{
		return
		((int(*)(void* __self, const char* __blockName, void* __data, int __count))g_assetsystem_nativeFunctions[93])(m_pSelf, blockName, data, count);
	}
	inline const CUtlBuffer* GetOverrideData() 
	{
		return
		((const CUtlBuffer*(*)(void* __self))g_assetsystem_nativeFunctions[94])(m_pSelf);
	}
	inline const CResourceStream* Data() 
	{
		return
		((const CResourceStream*(*)(void* self))g_assetsystem_nativeFunctions[95])(m_pSelf);
	}
	inline const CResourceStream* StreamingData() 
	{
		return
		((const CResourceStream*(*)(void* self))g_assetsystem_nativeFunctions[96])(m_pSelf);
	}
	inline const IResourceCompilerContextChild* CreateChildContext(const char* pFileName) 
	{
		return
		((const IResourceCompilerContextChild*(*)(void* self, const char* pFileName))g_assetsystem_nativeFunctions[97])(m_pSelf, pFileName);
	}
};
class IResourceCompilerContextChild
{
	public:
	void *m_pSelf;
	inline operator IResourceCompilerContextChild*()
	{
		return (IResourceCompilerContextChild*)m_pSelf;
	}
	inline void SetOverrideInputData(const char* data) 
	{
		((void(*)(void* __self, const char* __data))g_assetsystem_nativeFunctions[98])(m_pSelf, data);
	}
	inline int CompileImmediately() 
	{
		return
		((int(*)(void* self))g_assetsystem_nativeFunctions[99])(m_pSelf);
	}
};
#undef ConVar
#undef ConCommand
#undef CUtlBuffer
#undef CUtlString
#undef CUtlVector
inline void assetsystemFree()
{
	if ( g_passetsystemLibrary == 0 ) return;
	FreeLibrary( (HMODULE)g_passetsystemLibrary );
	g_passetsystemLibrary = 0;
	g_bIsassetsystemInitialized = false;
}
#endif
